<?php
// module/Pinnacle/view/pinnacle/booking/hotlistadd.phtml:


$title = 'Add to Hotlist';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');
//$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/layout.css');
 
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.9.1.js');//
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
//$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');

//$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/jquery.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');
//$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/layout.js?ver=1.0.2', 'text/javascript');

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');

$this->headScript()->appendFile($this->basePath() . '/js/tabs.js', 'text/javascript');
$this->headLink()->prependStylesheet($this->basePath() .'/css/tabs.css');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
	/*if($_POST["running_dates"]=="")
		$running_dates = "['2014-03-13', '2014-02-02', '2014-02-03', '2014-02-05']";
	else
		$running_dates = $_POST["running_dates"];*/
		
		//$running_dates = "['2014-03-13', '2014-02-02', '2014-02-03', '2014-02-05']"; 
?>
<style type="text/css">
 .ui-autocomplete-loading { 
background: white url('/public/img/images/ui-anim_basic_16x16.gif') right center no-repeat;
}
</style>
<script>
<?php if(isset($_POST)) { ?>
var running_dates = <?php echo $_POST["running_dates"]; ?>;
var overtime_dates = <?php echo $_POST["overtime_dates"]; ?>;
var night_dates = <?php echo $_POST["night_dates"]; ?>;
var weekend_dates = <?php echo $_POST["weekend_dates"]; ?>;
var holiday_dates = <?php echo $_POST["holiday_dates"]; ?>;
<?php } ?>

function pageLoad() { //need to force calendar load
            //$( "#date" ).datepicker({altFormat: "yy-mm-dd",  altField: "#hidden_date"});
			
			$( "#depart_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#depart_date"});
			$( "#return_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#return_date"});
			
		$('#bookingform').on('submit', function(e){        
			if(!validateForm())
				e.preventDefault();		
		});
		
		//autocomplete for phys
		$( "#physician" ).autocomplete({
		source: function( request, response ) {//"/public/ajax/searchPhys", 
		
		$.ajax({    
	type: "GET",
	data: { term: $('#physician').val()	},
    url: "<?php echo $this->basePath();?>/ajax/searchPhys",	
    // The key needs to match your method's input parameter (case-sensitive).    
    contentType: "application/json; charset=utf-8",
    dataType: "json",
    success: function(data){  
	response( $.map( data, function(item) {
                // your operation on data
				 return {
				id: item.id,
				label: item.label,
				value: item.value
				}
            }));
	},
    failure: function(errMsg) {
        alert(errMsg);
    }
	});
		},//end source
		 select: function( event, ui ) {
			//alert(ui.item.id);
			$( "#physid" ).val(ui.item.id);
		},
		minLength: 3,
		 open: function() {
			$( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
		},
		close: function() {
			$( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
		}
});

//autocomplete for client
$( "#client" ).autocomplete({
		source: function( request, response ) {//"/public/ajax/searchCli", 
		
		$.ajax({    
	type: "GET",
	data: { term: $('#client').val()	},
    url: "<?php echo $this->basePath();?>/ajax/searchCli",	
    // The key needs to match your method's input parameter (case-sensitive).    
    contentType: "application/json; charset=utf-8",
    dataType: "json",
    success: function(data){  
	response( $.map( data, function(item) {
                // your operation on data
				 return {
				id: item.id,
				label: item.label,
				value: item.value
				}
            }));
	},
    failure: function(errMsg) {
        alert(errMsg);
    }
	});
		},//end source
		 select: function( event, ui ) {
			//alert(ui.item.id);
			$( "#clientid" ).val(ui.item.id);
		},
		minLength: 3,
		 open: function() {
			$( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
		},
		close: function() {
			$( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
		}
});
			
}
		
function validateForm()
{
	var valid=true;
	if($( "#physician" ).val()==""){
		valid=false;
		alert('You need to select a physician');
		
	}	
	if($( "#billable:checked" ).val()!=1 && $( "#billable:checked" ).val()!=0){
		alert('You need to select billable/non-billable');
		valid=false;
	}
	if($( "#client" ).val()==""){
		valid=false;
		alert('You need to select a client');
		
	}
	if($( "#client" ).val()==""){
		valid=false;
		alert('You need to enter a city');		
	}
	
	if(valid==true)
		return true;
	else
		return false; //return false to prevent postback
}

</script>

<a id="top" name="top" ></a>

	<a href="<?php echo $this->basePath(); ?>/booking/hotlistindex">Back to Hotlist</a>
	
<h1 ><?php //echo $this->escapeHtml($title); ?></h1>
<br/>
<?php
    
    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));

    echo $this->form()->openTag($form);
	//echo var_dump($_POST);
?>

<p style="text-align:center; color: red"><?php echo $message; ?></p>
 
  
  

 <h3>Add to Hotlist</h3>
 <div class="row">
    <div class="span4">
        <label>Name:</label> <input type="text" name="name" id="name" value="<?php echo $_POST["name"];?>" />
    </div>
   
	<div class="span4">
        
    </div>
</div>
<div class="row">
    <div class="span4">
        <label>Last Contact:</label> <input type="text" name="last_contact" id="last_contact" value="<?php echo $_POST["last_contact"];?>" />
    </div>
	<div class="span4">
        <label>When:</label> <input type="text" name="when" id="when" value="<?php echo $_POST["when"];?>" />
    </div>
	
</div>
 <div class="row">
    <div class="span4">
        <label>Location:</label> <input type="text" name="location" id="location" value="<?php echo $_POST["location"];?>" />
    </div>
	<div class="span4">
        <label>Type:</label> <input type="text" name="type" id="type" value="<?php echo $_POST["type"];?>" />
    </div>
</div>
 <div class="row">
    <div class="span4">
        <label>Notes:</label> <textarea name="notes" ><?php echo $_POST["notes"];?></textarea>
    </div>
    <div class="span4">
        
    </div>
	<div class="span4">
        
    </div>
</div>
  
 

<br/>

<a href="#top">Back to Top</a><br/><br/>

<input type="submit" value="Submit" name="submit" id="submit" class="btn btn-large" />
<input type="button" value="Cancel" class="btn btn-large" id="cancel"/>  

<script>
pageLoad();

</script>


<?php

echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
