<?php
// module/Pinnacle/view/pinnacle/booking/hotlistadd.phtml:


$title = 'Hotlist';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');
//$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/layout.css');
 
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.9.1.js');//
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
//$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');

//$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/jquery.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');
//$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/layout.js?ver=1.0.2', 'text/javascript');

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');

$this->headScript()->appendFile($this->basePath() . '/js/tabs.js', 'text/javascript');
$this->headLink()->prependStylesheet($this->basePath() .'/css/tabs.css');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
	/*if($_POST["running_dates"]=="")
		$running_dates = "['2014-03-13', '2014-02-02', '2014-02-03', '2014-02-05']";
	else
		$running_dates = $_POST["running_dates"];*/
		
		//$running_dates = "['2014-03-13', '2014-02-02', '2014-02-03', '2014-02-05']"; 
?>
<style type="text/css">
 .ui-autocomplete-loading { 
background: white url('/public/img/images/ui-anim_basic_16x16.gif') right center no-repeat;
}
.hottable { width: 80%; margin-right: auto; margin-left: auto;  }
.hottable tr { border: 1px solid #cccccc; }
.hottable td { border: 1px solid #cccccc; padding: 5px; }
</style>


<a id="top" name="top" ></a>

	
	
<h1 ><?php //echo $this->escapeHtml($title); ?></h1>
<br/>
<?php
    
    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));

    echo $this->form()->openTag($form);
	//echo var_dump($_POST);
?>

<p style="text-align:center; color: red"><?php echo $message; ?></p>
 
  
  

 <h3>Hotlist</h3>
 <a href="<?php echo $this->basePath(); ?>/booking/hotlistadd">Add to Hotlist</a>
 <div class="row">
    <div class="span12">
        <?php
		if(count($arr)>0)
		{
		echo '<table class="hottable"><tr><th>Name</th><th>Last Contact</th><th>When</th><th>Location</th><th>Notes</th></tr>';
		foreach($arr as $key=>$val)
		{
			$table.='<tr><td><a href="'.$this->basePath().'/booking/hotlistedit/'.$val["id"].'">'.$val["name"].'</a></td><td>'.$val["last_contact"].'</td><td>'.$val["when"].'</td><td>'.$val["location"].'</td><td>'.substr($val["notes"],0,50).'...</td></tr>';
		}
		echo $table;
		echo '</table>';
		}
		else{
			echo '<p style="text-align:center; color: red">No records to display!</p>';
		}
		?>
    </div>
   
	
</div>

  
 


<script>
pageLoad();

</script>


<?php

echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
