<?php
// module/Pinnacle/view/pinnacle/booking/index.phtml:
// Contract Search

$title = 'Bookings';
$this->headTitle($title);


$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
//    $form->setAttribute('action', $this->url('resort', array('action'=>'booking')));

    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));

    echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="span4" >
	<p style="">
	<a href="<?php echo $this->basePath(); ?>/booking/view/add">Create Booking</a>
	</p>
	</div>
	<div class="span2" >
	<p style="">
	<a href="<?php echo $this->basePath(); ?>/booking/monthtotals">Monthly Totals Report</a>
	</p>
	</div>
</div>
<div class="row">
    <div class="span6">
	
	<?php	
		
		//echo var_dump($arr);
		
		if(count($arr)>0)
		{
			//echo "test";
			echo '<table class="table report">';
			echo "<tr><th><a href='?sort=idbookings'>#</a></th><th><a href='?sort=clienttxt'>Client</a></th><th><a href='?sort=physname'>Physician</a></th><th></th></tr>";
			foreach($arr as $key=>$val)
			{
				echo "<tr><td>".$val["id"]."</td><td><a href='".$this->basePath()."/booking/view/".$val["id"]."/edit'>".$val["client"]."</a></td><td>".$val["physician"]."</td><td><a href='".$this->basePath()."/booking/totals/".$val["id"]."'>Totals</a></td></tr>";
			}
			
			
			echo '</table>';
		}
	?>
        
    </div>
</div>
<?php
    echo $this->form()->closeTag();
?>

<?php
echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
