<?php
// module/Pinnacle/view/pinnacle/booking/locumstats.phtml:
// booking view

$title = 'Locums Stats';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');
//$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/layout.css');
 
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.9.1.js');//
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
//$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');

//$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/jquery.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');
//$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/layout.js?ver=1.0.2', 'text/javascript');

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');

$this->headScript()->appendFile($this->basePath() . '/js/tabs.js', 'text/javascript');
$this->headLink()->prependStylesheet($this->basePath() .'/css/tabs.css');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
	/*if($_POST["running_dates"]=="")
		$running_dates = "['2014-03-13', '2014-02-02', '2014-02-03', '2014-02-05']";
	else
		$running_dates = $_POST["running_dates"];*/
		
		//$running_dates = "['2014-03-13', '2014-02-02', '2014-02-03', '2014-02-05']"; 
?>
<style type="text/css">
 .ui-autocomplete-loading { 
background: white url('/public/img/images/ui-anim_basic_16x16.gif') right center no-repeat;
}
</style>


<a id="top" name="top" ></a>

	
	
<h1 ><?php //echo $this->escapeHtml($title); ?></h1>
<br/>
<?php
    
    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));

    echo $this->form()->openTag($form);
	//echo var_dump($_POST);
?>

<p style="text-align:center; color: red"><?php echo $message; ?></p>
 
 <h3>Enter Locums Stats</h3>
 
 <div class="row">
    <div class="span4">
        <label>Employee:</label> <input type="text" name="emp_id" id="emp_id" value="<?php echo $arr["emp_id"];?>" />
    </div>
    
	<div class="span4">
        Larry Benjamin=273, MJ=256, Donna=240, Clark=234
    </div>
</div>

 <div class="row">
    <div class="span4">
        <label>YTD:</label> <input type="text" name="ytd" id="ytd" value="<?php echo $arr["ytd"];?>" />
    </div>
    
	<div class="span4">
        
    </div>
</div>

 <div class="row">
    <div class="span4">
        <label>Yearly Goal:</label> <input type="text" name="yearly_goal" id="yearly_goal" value="<?php echo $arr["yearly_goal"];?>" />
    </div>
</div>

 <div class="row">
    <div class="span4">
        <label>Monthly Goal:</label> <input type="text" name="monthly_goal" id="monthly_goal" value="<?php echo $arr["monthly_goal"];?>" />
    </div>
</div>

 <div class="row">
    <div class="span4">
        <label>Current Month:</label> <input type="text" name="current_mon" id="current_mon" value="<?php echo $arr["current_mon"];?>" />
    </div>
</div>

 <div class="row">
    <div class="span4">
        <label>Next Month:</label> <input type="text" name="next_mon" id="next_mon" value="<?php echo $arr["next_mon"];?>" />
    </div>
</div>

 <div class="row">
    <div class="span4">
        <label>Net Added/Deleted:</label> <input type="text" name="net_add" id="net_add" value="<?php echo $arr["net_add"];?>" /> (use - for negative)
    </div>
</div>

 <div class="row">
	<div class="span6">
        <label>Outstanding Contracts:</label> <textarea style="width:100%" name="outstanding_contracts" id="outstanding_contracts" ><?php echo $arr["outstanding_contracts"];?></textarea>
    </div>
</div>

 <div class="row">
	<div class="span6">
        <label>Open Positions:</label> <textarea style="width:100%" name="open_positions" id="open_positions" ><?php echo $arr["open_positions"];?></textarea>
    </div>
</div>


 



<br/>
<p id="date22"></p>
<a href="#top">Back to Top</a><br/><br/>

<input type="submit" value="Submit" name="submit" id="submit" class="btn btn-large" />
  

<script>
pageLoad();

</script>


<?php

echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
