<?php
// module/Pinnacle/view/pinnacle/booking/pcstats.phtml:
// booking view

$title = 'PhysicianCareer Stats';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');
//$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/layout.css');
 
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.9.1.js');//
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
//$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');

//$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/jquery.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');
//$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/layout.js?ver=1.0.2', 'text/javascript');

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');



if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
	/*if($_POST["running_dates"]=="")
		$running_dates = "['2014-03-13', '2014-02-02', '2014-02-03', '2014-02-05']";
	else
		$running_dates = $_POST["running_dates"];*/
		
		//$running_dates = "['2014-03-13', '2014-02-02', '2014-02-03', '2014-02-05']"; 
?>
<style type="text/css">
 .ui-autocomplete-loading { 
background: white url('/public/img/images/ui-anim_basic_16x16.gif') right center no-repeat;
}
</style>


<a id="top" name="top" ></a>

	
	
<h1 ><?php //echo $this->escapeHtml($title); ?></h1>
<br/>
<?php
    
    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));
//echo date('m');
    echo $this->form()->openTag($form);
	//echo var_dump($_POST);
?>

<p style="text-align:center; color: red"><?php echo $message; ?></p>
 
 <h3>Enter PhysicianCareer Stats</h3>
 <div class="row">
    <div class="span4">
        <label>Monthly Goal:</label> <input type="text" name="monthly_goal" id="monthly_goal" value="<?php echo $arr["monthly_goal"];?>" />
    </div>
    
	<div class="span4">
        
    </div>
</div>

 <div class="row">
    <div class="span4">
        <label>Month Total (so far):</label> <input type="text" name="monthly_amt" id="monthly_amt" value="<?php echo $arr["monthly_amt"];?>" />
    </div>
</div>

 <div class="row">
    <div class="span4">
        <label>Year Goal:</label> <input type="text" name="yearly_goal" id="yearly_goal" value="<?php echo $arr["yearly_goal"];?>" />
    </div>
</div>

 <div class="row">
    <div class="span4">
        <label>Year Total (so far):</label> <input type="text" name="yearly_amt" id="yearly_amt" value="<?php echo $arr["yearly_amt"];?>" />
    </div>
</div>
 


 



<br/>


<input type="submit" value="Submit" name="submit" id="submit" class="btn btn-large" />
 

<script>
pageLoad();

</script>


<?php

echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
