<?php
// module/Pinnacle/view/pinnacle/mail/index.phtml:

$title = 'Create Email';
$this->headTitle($title);
$this->inlineScript()->appendFile($this->basePath() . '/js/maillist.js', 'text/javascript');
if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<script src="//tinymce.cachefly.net/4.1/tinymce.min.js"></script>
<script>tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
</script>


<h1><?php echo $this->escapeHtml($title); ?></h1>


<?php
    /*$form->setAttribute('action', $this->url('resort', array('action'=>'mdesedit')));
    $form->get('uid')->setValue($phguser->uid);
    $form->get('description')->setLabelAttributes(array('style'=> 'vertical-align: top; margin-top: 5px'));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('uid'));
    echo $this->formHidden($form->get('list_id')); // #my-list
    echo $this->formHidden($form->get('shared'));*/
?>

<p style='text-align:center; color:red'><?php echo $message; ?></p>
   <form action="" method="post"> 
    <div class="row" >
        <div class="span10">
            
        </div>
    </div>
	<div class="row" >
        <div class="span10">
            <label>Title:</label>
			<input type="text" name="title" />

        </div>
    </div>
	<div class="row" >
        <div class="span10">
            <label>From Address:</label>
			<input type="text" name="fromaddr" />

        </div>
    </div>
	<div class="row" >
        <div class="span10">
            <label>Subject:</label>
			<input type="text" name="subject" />

        </div>
    </div>
	 <div class="row" >
        <div class="span10">
		<label>Body:</label>
            <textarea name="body"></textarea>

        </div>
    </div>
	
	<br/><br/>
	<div class="row" >
        <div class="span10">
            <label>List:</label>
			<select name="lists" >
			<?php
				foreach ($mlists as $key=>$val)
				{
					echo '<option value="'.$key.'">'.$val.'</option>';
				}
			?>
			</select>

        </div>
    </div>
	
	<div class="row" >
        <div class="span10"><br/>
				<input type="submit" name="submit" value="Save" class="btn" />
        </div>
    </div>
	
	</form>
<?php
    //echo $this->form()->closeTag();
?>


<?php
/*$url = $this->url('resort', array('action'=>'mdes')); // . add / edit / del
$lurl = $this->url('mail', array('action'=>'list', 'part' => 'L')); // . lid/1
$redir = $this->url('login');
$scrip = "mlMainInit(\"$lurl\", \"$url\", \"$redir\");\n";
$this->inlineScript()->appendScript($scrip, 'text/javascript');*/

//echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-mis'));
