<?php
// module/Pinnacle/view/pinnacle/mail/deletemail.phtml:

$title = 'Emails';
$this->headTitle($title);
$this->inlineScript()->appendFile($this->basePath() . '/js/maillist.js', 'text/javascript');
if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<p style="text-align:center; color:red"><?php echo $message; ?></p>
<?php
   /* $form->setAttribute('action', $this->url('resort', array('action'=>'mdesedit')));
    $form->get('uid')->setValue($phguser->uid);
    $form->get('description')->setLabelAttributes(array('style'=> 'vertical-align: top; margin-top: 5px'));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('uid'));
    echo $this->formHidden($form->get('list_id')); // #my-list
    echo $this->formHidden($form->get('shared'));*/
?>
    <!--<button type="button" class="close" data-dismiss="alert" title="Cancel">&times;</button>//-->
    <div class="row" style="vertical-align: top">
        <div class="span3">
			<a href="<?php echo $this->basePath(); ?>/mail/addemail">Create Email</a>
            
        </div>
        <div class="span6">
            <?php //echo $this->formRow($form->get('description')); ?>
        </div>
        <div class="span1">
            <?php //echo $this->formButton($form->get('editbutton')); ?>
        </div>
    </div>
	
	
<?php
    //echo $this->form()->closeTag();
?>







<?php
$url = $this->url('resort', array('action'=>'mdes')); // . add / edit / del
$lurl = $this->url('mail', array('action'=>'list', 'part' => 'L')); // . lid/1
$redir = $this->url('login');
$scrip = "mlMainInit(\"$lurl\", \"$url\", \"$redir\");\n";
$this->inlineScript()->appendScript($scrip, 'text/javascript');

//echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-mis'));
