<?php
// module/Pinnacle/view/pinnacle/mail/index.phtml:

$title = 'Mailing Lists';
$this->headTitle($title);
$this->inlineScript()->appendFile($this->basePath() . '/js/maillist.js', 'text/javascript');
if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="hidden alert alert-block" id="my-form-div">
<?php
    $form->setAttribute('action', $this->url('resort', array('action'=>'mdesedit')));
    $form->get('uid')->setValue($phguser->uid);
    $form->get('description')->setLabelAttributes(array('style'=> 'vertical-align: top; margin-top: 5px'));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('uid'));
    echo $this->formHidden($form->get('list_id')); // #my-list
    echo $this->formHidden($form->get('shared'));
?>
    <button type="button" class="close" data-dismiss="alert" title="Cancel">&times;</button>
    <div class="row" style="vertical-align: top">
        <div class="span3">
            <?php echo $this->formRow($form->get('name')); ?>
        </div>
        <div class="span6">
            <?php echo $this->formRow($form->get('description')); ?>
        </div>
        <div class="span1">
            <?php echo $this->formButton($form->get('editbutton')); ?>
        </div>
    </div>
<?php
    echo $this->form()->closeTag();
?>
</div>
<div class="hidden alert" id="my-confirm-div">
    Are you sure?
    <button class="btn btn-warning btn-small" type="button" id="my-confirm-yes">YES</button>
    <button class="btn btn-small" type="button" id="my-confirm-no">NO</button>
</div>

<div class="row">
    <div class="span4" id="searchstatus"></div>
    <div class="pull-right span4 input-append">
        <input class="span3" id="my-new-name" type="text" required='required' placeholder="New List Name..."
            title="Create new list">
        <button class="btn" type="button" id="my-list-add"><i class="icon-plus"></i> New</button>
    </div>
</div>

<table class="table">
<thead><tr>
    <th>List#</th>
    <th>Name</th>
    <th>Description</th>
    <th>Date</th>
    <th>Action</th>
</tr></thead>
<tbody id="my-tbody">
<?php foreach ($report as $row) : ?>
<tr id="my-row-<?php echo $this->escapeHtml($row->list_id);?>">
    <td><a href="<?php echo $this->url('mail', array('action'=>'list', 'part'=> "L$row->list_id", 'id' => 1)) ?>">
        <?php echo $this->escapeHtml($row->list_id);?> </a></td>
    <td><?php echo $this->escapeHtml($row->name);?></td>
    <td><?php echo $this->escapeHtml($row->description);?></td>
    <td><?php echo $this->escapeHtml($row->formatDate($row->date_mod));?></td>
    <td><a href="#" data-list-id="<?php echo $this->escapeHtml($row->list_id);?>" class="my-listedit btn btn-small"><i class="icon-pencil"></i> Edit</a>
        <a href="<?php echo $this->basePath(); ?>/mail/deletelist/<?php echo $row->list_id;?>" onclick="return confirm('Are you sure you want to delete?');" data-list-id="<?php echo $this->escapeHtml($row->list_id);?>" class="my-listdel btn btn-small btn-danger"><i class="icon-trash icon-white"></i> Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>

<?php
$url = $this->url('resort', array('action'=>'mdes')); // . add / edit / del
$lurl = $this->url('mail', array('action'=>'list', 'part' => 'L')); // . lid/1
$redir = $this->url('login');
$scrip = "mlMainInit(\"$lurl\", \"$url\", \"$redir\");\n";
$this->inlineScript()->appendScript($scrip, 'text/javascript');

//echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-mis'));
