<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <!--[if IE]><![endif]-->
        <?php
        echo $this->headTitle('PHG Database')->setSeparator(' - ')->setAutoEscape(false);
        $this->headMeta()
            ->appendName('application-name', 'PHG Database')
            ->appendName('author', 'Sergey Latkin / Nathan Turner')
            ->appendName('description', 'The Database');
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/main.css', array('media' => 'screen,print') )
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
            echo $this->headStyle(); // inline styles
?>

        <!-- Scripts -->
		<?php echo $this->headScript()->prependFile($this->basePath() . '/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js', 'text/javascript'); ?>
		<?php //echo $this->headScript()->prependFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript'); ?>
        
		<?php echo $this->headScript()->prependFile('http://code.jquery.com/jquery-1.11.0.js', 'text/javascript'); ?>
		
    </head>
    <body style="background-color: #F0F9FE">
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
        <![endif]-->

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">Pinnacle Health Group</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav ">
                            <li id="phg-nav-act" class="dropdown active">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('home') ?>"><i class="icon-home"></i> Home</a></li>
                                    <li><a href="<?php echo $this->url('calendar') ?>"><i class="icon-calendar"></i> Calendar</a></li>
                                    <li><a href="<?php echo $this->url('mail') ?>"><i class="icon-list"></i> Manage Lists</a></li>
                                    <li><a href="#"><i class="icon-envelope"></i> Mass Email</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url('preference') ?>"><i class="icon-wrench"></i> Preferences</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url('logout') ?>"><i class="icon-off"></i> Log Out</a></li>
                                </ul>
                            </li>
                            <li id="phg-nav-cli"><a href="<?php echo $this->url('client') ?>">Clients</a></li>
                            <li id="phg-nav-ctr"><a href="<?php echo $this->url('contract') ?>">Contracts</a></li>
                            <li id="phg-nav-pro" class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Providers <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('physician') ?>"><i class="icon-plus-sign"></i> Physician</a></li>
                                    <li><a href="<?php echo $this->url('midlevel') ?>"><i class="icon-screenshot"></i> Mid-Level</a></li>
                                    <li><a href="<?php echo $this->url('booking') ?>"><i class="icon-pencil"></i> Bookings</a></li>									
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url('mail') ?>"><i class="icon-list"></i> Mail Lists</a></li>
                                </ul>
                            </li>
                            <li id="phg-nav-loo"><a href="<?php echo $this->url('lookup') ?>">Look-up</a></li>
							<!--<li id="phg-nav-geo"><a href="<?php //echo $this->url('lookup', array('action'=>'geozip')) ?>">Geozip</a></li>-->
                            <li id="phg-nav-rep" class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('report', array('action'=>'list', 'part'=>'market')) ?>"><i class="icon-flag"></i> Marketing</a></li>
                                    <li><a href="<?php echo $this->url('report', array('action'=>'list', 'part'=>'recruit')) ?>"><i class="icon-star"></i> Recruiting</a></li>
                                    <li><a href="<?php echo $this->url('report', array('action'=>'list', 'part'=>'locums')) ?>"><i class="icon-fire"></i> Locum Tenens</a></li>
                                    <li><a href="<?php echo $this->url('report', array('action'=>'list', 'part'=>'common')) ?>"><i class="icon-file"></i> Common</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Administrative</li>
                                    <li><a href="<?php echo $this->url('report', array('action'=>'list', 'part'=>'admin')) ?>"><i class="icon-user"></i> Admin Reports</a></li>
                                    <li><a href="<?php echo $this->url('report', array('action'=>'list', 'part'=>'fuzion')) ?>"><i class="icon-info-sign"></i> Physician Career</a></li>
                                    <li><a href="<?php echo $this->url('report', array('action'=>'list', 'part'=>'source')) ?>"><i class="icon-folder-open"></i> Sourcing</a></li>
                                    <li><a href="<?php echo $this->url('report', array('action'=>'list', 'part'=>'vital')) ?>"><i class="icon-heart"></i> Vital Stats</a></li>
                                </ul>
                            </li>
                            <li id="phg-nav-mis" class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Misc <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#"><i class="icon-bell"></i> Help (Site Map)</a></li>
                                    <li><a href="<?php echo $this->url('linx') ?>"><i class="icon-globe"></i> Useful Links</a></li>
                                    <li><a href="/manual/index.htm" target="_blank"><i class="icon-briefcase"></i> Employee Handbook</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Admin Actions</li>
                                    <li><a href="<?php echo $this->url('admin') ?>"><i class="icon-user"></i> Manage Users</a></li>
                                    <li><a href="<?php echo $this->url('admin', array('action'=>'goals')) ?>"><i class="icon-edit"></i> Manage Goals</a></li>
                                    <li><a href="<?php echo $this->url('contract', array('action'=>'managesources')) ?>"><i class="icon-share"></i> Manage Sources</a></li>
                                    <li><a href="<?php echo $this->url('admin', array('action'=>'cleanup')) ?>"><i class="icon-remove-sign"></i> Database Cleanup</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">
            <?php echo $this->content; ?>

            <hr>
            <footer>
                <p>&copy; 2014 All rights reserved.</p>
            </footer>
        </div> <!-- /container -->
        <?php
            $jQalt = <<<HereScript1
            window.jQuery || document.write('<script src="/js/vendor/jquery-1.8.3.min.js"><\/script>');
HereScript1;
            $googAn = <<<HereScript2
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
HereScript2;
            echo $this->inlineScript()
        //    ->appendScript($googAn, 'text/javascript') // enable for google analytics
            ->prependFile($this->basePath() . '/js/main.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/vendor/polyfiller.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/vendor/bootstrap.min.js', 'text/javascript');
			//->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.0/jquery.min.js');
            //->prependScript($jQalt, 'text/javascript')
            //->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'); ?>
    </body>
</html>
