<?php
// module/Pinnacle/view/pinnacle/midlevel/view.phtml:
// Contract Search
$ctrid = $_GET["ctr_id"];
$contid = $_GET["cont_id"];

$titul = "Pre-profile letter for " .$ar["ctr_no"];
$title = "Pre-profile letter for " .$ar["ctr_no"];
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');

//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');
/*
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');*/

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<style>

</style>


<?php

?>

<h1 ><?php echo $this->escapeHtml($title); ?></h1>
<br/>
<?php
    //$form->setAttribute('action', $this->url('resort', array('action'=>'midlevels')));
    //$form->get('submit')->setAttribute('type','button');
  
    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));

    echo $this->form()->openTag($form);
	//echo var_dump($ar);
?>

<p style="text-align:center; color: red"><?php echo $message; ?></p>

<div id="spacer">
<p><?php echo date('Y-m-d'); ?></p>
<p>&nbsp; </p>
<p><?php echo $ar["cont_name"]; ?><br>

<?php if($ar["cont_title"]!=""){ echo $ar["cont_title"]."<br/>"; } ?>
<?php echo $ar["ctct_name"]; ?><br>
<?php if($ar["addr1"]!=""){ echo $ar["addr1"]."<br/>"; } ?>
<?php if($ar["addr2"]!=""){ echo $ar["addr2"]."<br/>"; } ?>

<?php echo $ar["city"]; ?>, <?php echo $ar["stat"]; ?>&nbsp;<?php echo $ar["zip"]; ?></p>
<p>&nbsp; </p>
<p align="right">#<?php echo $ar["ctr_no"]; ?></p>
<p>Dear <?php echo $ar["cont_name"]; ?>:</p>
<p>I look forward to working with you regarding the search for a <?php echo $spec; ?> at<?php echo $ar["ctct_name"]; ?> . Please complete and return the enclosed Group, Community, and Hospital Profile forms and fax them to me at (404) 816-7853 so that I may review them prior to my scheduled visit.</p>
<p>It would be of great benefit to include a meeting with all individuals who will be involved in the decision making process. Please arrange for a tour of the community, hospital, and office facilities.</p>
<p>These profiles will enable me to develop a systematic strategy for your search. It is my firm belief that, in taking the time to work together, we will be successful.</p>
<p>I look forward to meeting with you on <?php echo $ar["ctr_pro_date"]; ?>.</p>
<p>Sincerely,</p>
<p>&nbsp; </p>
<p>&nbsp; </p>
<p><?php echo $ar["req_name"]; ?><br>
<?php echo $ar["req_title"]; ?></p>
<p>&nbsp; </p>
<p> Enclosures </p>
</div>





<div style="clear:both">&nbsp;</div>
<?php
    echo $this->form()->closeTag();
?>







<?php

echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
