<?php
// module/Pinnacle/view/pinnacle/physician/view.phtml:
// Contract Search

$title = 'Approve Contract Change';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');

//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');
/*
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');*/

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<style>
#phystable { width: 70% }
#datetable, #spectable, #phystable, .historytable { border: 1px solid black }
#datetable td, #spectable td, .historytable td { border: 1px solid black }
#phystable td { border: 1px solid black; background-color: #ffffff; }
.tab { /*common class for tabs*/ margin-left: auto; margin-right: auto; }
.hiddendiv { display: none; }
#physician_pass_div { display: none; }
#sched_activity_div { display: none; }
.date { width: 110px; }
.time { width: 60px; }
</style>


<?php
$type = $_GET["type"];
$ctr_id = $_GET["ctr_id"];
$pipl_id = $_GET["pipl_id"];

switch($type)
{
	case 1:
	$title="Place Search on Hold Request";
	$head1="Please place this search on hold for the following reason:";
	$head2="Please cancel the Sourcing Campaign.";
	break;
	case 2:
	$title="Reactivate Search Request";
	$head1="Please reactivate this search.";
	$head2="Please create a new Sourcing Campaign.";
	break;
	case 3:
	$title="Change of Specialty Request";
	$head1="Please change the specialty of this search to the following:";
	$head2="Please cancel Sourcing for old specialty and create a new campaign.";
	break;
	case 4:
	$title="Change of Recruiter Request";
	$head1="Please change the Recruiter of this search to the following:";
	$head2="Please change the Sourcing to reflect the new recruiter.";
	break;
	case 5:
	$title="Placement Write Off Request";
	$head1="Please write off the above placement and begin a replacement search for the following reason:";
	$head2="Please reactivate the Sourcing.";
	break;
	case 6:
	$title="Zombify Search Request";
	$head1="Please make this search zombie for the following reason:";
	$head2="Please keep existing sourcing campaign.";
	break;
}
?>

<h1 ><?php echo $this->escapeHtml($title); ?></h1>
<br/>
<?php
    //$form->setAttribute('action', $this->url('resort', array('action'=>'midlevels')));
    //$form->get('submit')->setAttribute('type','button');
  
    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));

    echo $this->form()->openTag($form);
	//echo var_dump($ar);
?>

<p style="text-align:center; color: red"><?php echo $message; ?></p>

<INPUT type="hidden" name="chg_ctr_id" value="<?php echo $ctr_id; ?>">
<INPUT type="hidden" name="chg_type" value="<?php echo $type; ?>">
<INPUT type="hidden" name="chg_pipl" value="<?php echo $pipl_id; ?>">
<div class="row">
    <div class="span12">
	<table border="0" cellpadding="2">
  <tr>
    <td><b>Date:</b></td>
    <td><?php echo $ar["ctr_date"]; ?>&nbsp;</td>
  </tr>
  <tr>
    <td><b>Recruiter:</b></td>
    <td><?php echo $ar["emp_uname"]; ?></td>
  </tr>
  <tr>
    <td><b>Contract#:</b></td>
    <td><?php echo $ar["ctr_no"]; if($ar["ctr_nurse"]){ echo " <strong>Mid-Level</strong>"; } ?> </td>
  </tr>
  <tr>
    <td><b>Client:</b></td>
    <td><?php echo $ar["ctct_name"]; ?></td>
  </tr>
  <tr>
    <td><b>City, State:</b></td>
    <td><?php echo $ar["ctct_addr_c"]; ?>, <?php echo $ar["ctct_st_code"]; ?></td>
  </tr>
  <tr>
    <td><b>Phone:</b></td>
    <td><?php echo $ar["ctct_phone"]; ?>&nbsp;</td>
  </tr>
  <tr>
    <td><b>Specialty:</b></td>
    <td><?php echo $ar["at_name"]; ?> <?php echo $ar["sp_name"]; ?>&nbsp;</td>
  </tr>
  </table>
    </div>    
</div>

<div class="row">
    <div class="span12">  
	<br/>
	<p><label><?php echo $head1; ?><!--Please write off the above placement and begin a replacement search for the following reason:--></label></p>
	<?php
		if($type<2 || $type>=5)
		{
	?>		
		<textarea name="reason" id="reason" ></textarea>	
		<?php } ?>
		
		<?php
		if($type==3)
		{
			if($ar["ctr_nurse"]){ //get nurse specs
				echo '<label>Specialty</label><select  name="chg_nut" >';
				foreach($specs as $key=>$val)
				{
					echo "<option value='".$val["at_code"]."'>".$val["at_code"]." ".$val["at_name"]."</option>";
				}
				echo '</select>';
				//echo var_dump($specs);
			}
			else{
				//chg_spec
			}
		}	

		if($type==4)
		{
			echo '<select name="chg_req"  >';
			
			foreach ($rec as $key=>$val)
			{
				echo "<option value='".$key."'>";				
				echo $val;
				echo "</option>";
			}
			
			echo '</select>';
		}	
		?>
		
    </div>    
</div>

<div class="row">
    <div class="span12">
	<p><?php echo $head2; ?><!--Please reactivate the Sourcing.--></p>

		<label>Comments:</label>
		<textarea name="comments" id="comments" ></textarea>	
		
		
    </div>    
</div>


<input type="submit" name="submit" value="Submit" />








<div style="clear:both">&nbsp;</div>
<?php
    echo $this->form()->closeTag();
?>






<script>
pageLoad();

</script>
<?php

echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
