<?php
// module/Pinnacle/view/pinnacle/physician/export.phtml:
// Doctor Export

$title = 'Export to PhysicianCareer.Com';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');

//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');
/*
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');*/

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>



<h1 ><?php echo $this->escapeHtml($title); ?></h1>
<br/>
<?php
    //$form->setAttribute('action', $this->url('resort', array('action'=>'midlevels')));
    //$form->get('submit')->setAttribute('type','button');
  
    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));

    //echo $this->form()->openTag($form);
	//echo var_dump($ar);
?>

<p style="text-align:center; color: red"><?php echo $message; ?></p>

<form method="post" action="http://admin.fuzionhg.com/resnew.php" target="fuzion" onsubmit="window.setTimeout('closewin()',10)" name="expform">
<p><strong>Click this button to export this doc</strong>: <input name="submit2" type="submit" id="submit2" value="Export" style="font-weight:bold "></p>
<p>Or, copy all text from the field below and paste it into appropriate place on PhysicianCareer's Add New Record page. You have to be logged in to the admin site already.</p>
<textarea name="import" cols="80" rows="8" style="width: 500px">
&lt;?xml version="1.0" ?&gt;
&lt;profile&gt;&lt;phg_id&gt;<?php echo $ar["ph_id"]; ?>&lt;/phg_id&gt;
<?php
	$nm = $ar["ctct_name"];
	//$nm = "Smith Johnson";
	$inm = strpos($nm, ",");
	if($inm!==false){
		$lnm = substr($nm, 0, $inm);
		$fnm = trim(substr($nm, $inm+1));
	}
	else
	{
		$inm = strpos($nm, " ");
		if($inm!==false){
			$fnm = substr($nm, 0, $inm);
			$lnm = trim(substr($nm, $inm+1));
		}
		else
		{
			$lnm = $nm;
			$fnm = ".";
		}
	}
?>
&lt;fname&gt;&lt;![CDATA[<?php echo $fnm; ?>]]&gt;&lt;/fname&gt;&lt;lname&gt;&lt;![CDATA[<?php echo $lnm; ?>]]&gt;&lt;/lname&gt;&lt;mddo&gt;<?php echo $ar["ctct_title"]; ?>&lt;/mddo&gt;
&lt;addr1&gt;&lt;![CDATA[<?php echo $ar["ctct_addr_1"]; ?>]]&gt;&lt;/addr1&gt;&lt;addr2&gt;&lt;![CDATA[<?php echo $ar["ctct_addr_2"]; ?>]]&gt;&lt;/addr2&gt;&lt;city&gt;&lt;![CDATA[<?php echo $ar["ctct_addr_c"]; ?>]]&gt;&lt;/city&gt;&lt;state&gt;<?php echo $ar["ctct_st_code"]; ?>&lt;/state&gt;&lt;zip&gt;<?php echo $ar["ctct_addr_z"]; ?>&lt;/zip&gt;
<?php if($ar["ph_workaddr"]!=''){ ?>&lt;ofaddr1&gt;&lt;![CDATA[<?php echo $ar["ctct_waddr_1"]; ?>]]&gt;&lt;/ofaddr1&gt;&lt;ofaddr2&gt;&lt;![CDATA[<?php echo $ar["ctct_waddr_2"]; ?>]]&gt;&lt;/ofaddr2&gt;&lt;ofcity&gt;&lt;![CDATA[<?php echo $ar["ctct_waddr_c"]; ?>]]&gt;&lt;/ofcity&gt;&lt;ofstate&gt;<?php echo $ar["ctct_wst_code"]; ?>&lt;/ofstate&gt;&lt;ofzip&gt;<?php echo $ar["ctct_waddr_z"]; ?>&lt;/ofzip&gt;
<?php } ?>&lt;homephone&gt;<?php echo $ar["ctct_hphone"]; ?>&lt;/homephone&gt;&lt;cellphone&gt;<?php echo $ar["ctct_cell"]; ?>&lt;/cellphone&gt;&lt;officephone&gt;<?php echo $ar["ctct_phone"]; ?>&lt;/officephone&gt;&lt;officeext&gt;<?php echo $ar["ctct_ext1"]; ?>&lt;/officeext&gt;
&lt;email&gt;&lt;![CDATA[<?php echo $ar["ctct_email"]; ?>]]&gt;&lt;/email&gt;&lt;spec&gt;<?php echo $ar["ph_spec_main"]; ?>&lt;/spec&gt;&lt;spec_2nd&gt;&lt;![CDATA[<?php echo $ar["ph_subspec"]; ?>]]&gt;&lt;/spec_2nd&gt;
&lt;school&gt;&lt;![CDATA[<?php echo $ar["ph_med_school"]; ?>]]&gt;&lt;/school&gt;&lt;amg&gt;
<?php
	if($ar["ph_citizen"]=="AMG") { echo "1"; } else { echo "0"; }
?>
&lt;/amg&gt;&lt;bcbe&gt;<?php echo $ar["ph_spm_bc"]; ?>&lt;/bcbe&gt;&lt;bcbe_year&gt;<?php echo $ar["ph_spm_year"]; ?>&lt;/bcbe_year&gt;&lt;licensed&gt;&lt;![CDATA[<?php echo $ar["ph_licenses"]; ?>]]&gt;&lt;/licensed&gt;
&lt;pstatus&gt;
<?php
$pst=0;
	if($ar["ph_practice"]==1) 
		$pst=1;
	if($ar["ph_practice"]==2) 
		$pst=3;
	if($ar["ph_practice"]==3) 
		$pst=2;
	echo $pst;
?>
&lt;/pstatus&gt;&lt;visa_status&gt;
<?php
	if($ar["ph_citizen"]=="J1" || $ar["ph_citizen"]=="H1B") { echo trim($ar["ph_citizen"]); }
?>
&lt;/visa_status&gt;
&lt;avail_date&gt;<?php echo $ar["ph_avail"]; ?>&lt;/avail_date&gt;
&lt;pref_region&gt;<?php echo $ar["ph_pref_region"]; ?>&lt;/pref_region&gt;&lt;pref_states&gt;<?php echo $ar["ph_pref_state"]; ?>&lt;/pref_states&gt;&lt;languages&gt;&lt;![CDATA[<?php echo $ar["ph_lang"]; ?>]]&gt;&lt;/languages&gt;&lt;phg_source&gt;&lt;![CDATA[<?php echo $ar["psr_source"]; ?>]]&gt;&lt;/phg_source&gt;
&lt;/profile&gt;
</textarea></form>

<a href="<?php echo $this->basePath(); ?>/physician/view/<?php echo $ar["ph_id"]; ?>">Back to Physician</a>





<div style="clear:both">&nbsp;</div>
<?php
    echo $this->form()->closeTag();
?>






<script>
//pageLoad();

</script>
<?php

echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
