<?php
// module/Pinnacle/view/pinnacle/physician/index.phtml:
// Contract Search

$title = 'Physicians Lookup';
$this->headTitle($title);
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.js', 'text/javascript');
$this->inlineScript()->appendFile($this->basePath() . '/js/physicians.js', 'text/javascript');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $form->setAttribute('action', $this->url('resort', array('action'=>'physicians')));
    $form->get('submit')->setAttribute('type','button');
    if( strpos($phguser->dept,'R') !== false ) {
        //$form->get('ph_recruiter')->setValue($phguser->uid);
        $form->get('ph_status')->setValue(1);
    }
    $form->prepare();
    $maillist = $this->formRow($form->get('mail_list'));

    echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="span4">
        <?php echo $this->formRow($form->get('ph_id')); ?>
        <?php echo $this->formRow($form->get('ph_lname')); ?>
        <?php echo $this->formRow($form->get('ph_fname')); ?>
        <?php echo $this->formRow($form->get('ph_spec_main')); ?>
        <?php echo $this->formRow($form->get('ph_subspec')); ?>
        <?php echo $this->formRow($form->get('ph_pref_region')); ?>
    </div>
    <div class="span4">
        <?php echo $this->formRow($form->get('ph_status')); ?>
        <?php echo $this->formRow($form->get('ph_citizen')); ?>
        <?php echo $this->formRow($form->get('ph_licenses')); ?>
        <?php echo $this->formRow($form->get('ctct_st_code')); ?>
        <?php echo $this->formRow($form->get('ph_pref_state')); ?><br>
        <?php echo $this->formRow($form->get('orcond')); ?><br>
        <?php
            $box = $form->get('ph_locums');
            echo $this->formLabel($box, $this->formCheckbox($box), 'append');
			
			$box = $form->get('has_cv');
            echo $this->formLabel($box, $this->formCheckbox($box), 'append');
            //  echo $this->formRow($form->get('ph_locums'));
        ?><br>
        <?php
            $box = $form->get('instant');
            echo $this->formLabel($box, $this->formCheckbox($box), 'append');
            // echo $this->formRow($form->get('instant'));
        ?>
    </div>
    <div class="span4">
        <?php echo $this->formRow($form->get('ph_recruiter')); ?>
        <?php echo $this->formRow($form->get('date1')); ?>
        <?php echo $this->formRow($form->get('date2')); ?>
        <?php echo $this->formRow($form->get('ph_src_date')); ?>
        <br><br>
        <?php echo $this->formInput($form->get('submit')) ?>
        &nbsp; <a href="<?php echo $this->url('physician') ?>" id="resetbutton" class="btn btn-danger btn-large">Reset</a>
        <br><br>
        <?php echo $this->formRow($form->get('pg_size')); ?> <span id="pagespan">25</span>
    </div>
</div>
<?php
    echo $this->form()->closeTag();
?>
<div class="row">
    <div class="span2"><a href="<?php echo $this->url('physician',array('action'=>'add')) ?>">Add New Physician</a></div>
    <div class="span2" id="searchstatus"></div>
    <div class="span7 phg-rite" id="phy-pages">
        Please start typing
    </div>
</div>
<hr>
<table class="table report">
    <thead><tr>
        <th>ID#</th>
        <th>Name</th>
        <th>Spec</th>
        <th>City, State</th>
        <th>Status</th>
    </tr></thead>
    <tbody id="phy-tbody">
        <tr><td colspan="5"><i>Waiting for input...</i> </td></tr>
    </tbody>
</table>
<div id="emaillist"></div>

<div class="row" id="my-savelist-div">
    <div class="span5 form-inline">
        <?php echo $maillist ?>
        <button class="btn myml-class" type="button" id="my-list-save"><i class="icon-download-alt"></i> Save to List</button>
    </div>
    <div class="pull-right span3 input-append">
        <input class="span2 myml-class" id="my-new-name" type="text" required='required' placeholder="New List Name..."
            title="Create new list">
        <button class="btn myml-class" type="button" id="my-list-add"><i class="icon-plus"></i> Add List</button>
    </div>
</div>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<?php
$url = $this->url('resort', array('action'=>'physicians'));
$url2 = $this->url('resort', array('action'=>'mdes')); // . add / edit / del / get
$redir = $this->url('login');
$scrip = "phyInit(\"#phy-tbody\",\"#phy-pages\", \"$url\", \"$redir\", \"$url2\");\n";
$this->inlineScript()->appendScript($scrip, 'text/javascript');
echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
