<?php
// module/Pinnacle/view/pinnacle/midlevel/add.phtml:

$title =  'Add Midlevel';
$this->headTitle($title);
$this->inlineScript()->appendFile($this->basePath() . '/js/midlevels.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css'); 
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.9.1.js');//

$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');
//$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
//$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');
$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');
//$this->headScript()->appendFile($this->basePath() . '/js/physicians2.js', 'text/javascript');
if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<style>
.cour {font-family: courier }
.toplbl {width: 100px; display: block; float: left; padding-top: 4px; }
.instasearchtbl { width: 80%; margin-left: auto; margin-right: auto; border: 1px solid #666666; background-color: #eeeeee; }
.instasearchtbl td { border: 1px solid black; }
</style>
<script>
$(function() {
var timeyn = false; //used to stop instant search

$("#canceladd").click(function() { 
var strfname = $('#ph_fname').val();
var strlname = $('#ph_lname').val();
if(!timeyn && strlname.length>=2){
instaSearch();
} 

});

$("#ph_fname").keyup(function() { 
var strfname = $('#ph_fname').val();
var strlname = $('#ph_lname').val();
if(!timeyn && (strlname.length>=3 || strfname.length>=3)){
setTimeout(instaSearch, 1000);
//instaSearch();
} 
});

$("#ph_lname").keyup(function() { 
var strfname = $('#ph_fname').val();
var strlname = $('#ph_lname').val();
if(!timeyn && (strlname.length>=3 || strfname.length>=3)){
setTimeout(instaSearch, 1000);
} 
});

function instaSearch(){ //alert('test');
timeyn=true;
$("#namelookup").html("Loading...");
//alert(this.timeyn);
$.ajax({    
	type: "GET",
    url: "<?php echo $this->basePath();?>/ajax/searchPhysicians",	
    // The key needs to match your method's input parameter (case-sensitive).
    //data: JSON.stringify({ "backref": "test" }),
	data: { fname: $('#ph_fname').val(), 
	lname: $('#ph_lname').val(),
	path: <?php echo $this->basePath();?>	//$("#contactlist").val()	
	},
	//data: "backref=test",
    contentType: "application/json; charset=utf-8",
    dataType: "json",
    success: function(data){/*alert(data.message);*/ $("#namelookup").html(data.message); timeyn=false; },
    failure: function(errMsg) {
        alert(errMsg);
    }
	});
	//timeyn=false;
}

});



$(function() { //alert('test'); 
//var x=0;

$(function() {
 $( "#ph_availtxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#ph_avail"});
});

$(function() {
 $( "#ph_cv_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#ph_cv_date"});
});

$(function() {
 $( "#ph_1st_inqtxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#ph_1st_inq"});
});

});

</script>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if( true /*$phguser->access > 1*/ ) { 

    $form = $this->form;
    $form->setAttribute('action', $this->url('midlevel',
                        array('action' => 'add', 'part' => $part, 'id' => $id)));
						
    $form->prepare();

echo $this->form()->openTag($form);
?>

<p style="text-align:center; color:red"><?php echo $message; ?></p>
<input type="hidden" name="ph_id" value="<?php //echo $ar["ph_id"]; ?>"/>
<input type="hidden" name="ph_workaddr" value="<?php //echo $ar["ph_workaddr"];$this->basePath() ?>"/>
<input type="hidden" name="ph_xchg" value="">
<input type="hidden" name="basepath" value="<?php echo $this->basePath(); ?>">
<input type="hidden" name="n" value="
<?php
	if($_GET["srs"]!="")
	{
		$i=$_GET["n"];
		if ($i == "") { $i = 3; } else { $i = $i+2; }
		echo $i;
	}
?>
">
<input type="hidden" name="srs" value="<?php echo $_GET["srs"]; ?>"/>
<h4>Contact Information</h4>
<div class="row">
<div class="span4">
<label class="toplbl">First Name:</label><input type="text" name="an_fname" id="an_fname" size="60" maxlength="127" value='<?php echo $_POST["an_fname"]; ?>' />
</div>
<div class="span4">
<label class="toplbl">Last Name:</label><input type="text" name="an_lname" id="an_lname" size="60" maxlength="127" value='<?php echo $_POST["an_lname"]; ?>' />
</div>
</div>

<div class="row">
<div class="span4">
<label class="toplbl">Title:</label><input type="text" name="ctct_title" size="20" maxlength="63" value='<?php if(isset($_POST["ctct_title"])){echo $_POST["ctct_title"]; } else { echo "MD"; } ?>'>
</div>
<div class="span4">
<label class="toplbl">Status:</label>
<select name="an_status" id="an_status">
	<?php
	//echo var_dump($statuses);
			foreach ($statuses as $row=>$ar_statuses)
			{
			//echo var_dump($ar_statuses);
				echo "<option value='".$ar_statuses['st_id']."'";
				if($ar_statuses['st_id']==$_POST["an_status"])
					echo "selected";
				elseif($_POST["an_status"]=="" && $ar_statuses['st_id']==1)
					echo "selected";
				echo ">";				
				echo $ar_statuses['st_name'];
				echo "</option>";
			}
		?>
	</select>

</div>
</div>

<div class="row">
<div class="span12">
<p style="text-align:center; font-weight: bold">Name Lookup</p>

<div id="namelookup" ></div>
</div>

</div>
<hr/>
<div class="row">
<div class="span6">
<strong>Home Address:</strong>
<table>
<tr>
<td>Line 1:</td><td colspan="2"><input type="text" name="ctct_addr_1" size="40" maxlength="63" value='<?php echo $_POST["ctct_addr_1"]; ?>' /></td>
</tr>
<tr>
<td>Line 2:</td><td colspan="2"><input type="text" name="ctct_addr_2" size="40" maxlength="63" value='<?php echo $_POST["ctct_addr_2"]; ?>' /></td>
</tr>
<tr>
<td>City:</td><td colspan="2"><input type="text" name="ctct_addr_c" size="40" maxlength="63" value='<?php echo $_POST["ctct_addr_c"]; ?>' /></td>
</tr>
<tr>
<td>State:</td><td>
<select name="ctct_st_code" id="ctct_st_code">
	<?php
	//echo var_dump($states);
			foreach ($states as $key=>$val)
			{
			//echo var_dump($ar_statuses);
				echo "<option value='".$key."'";
				if($key==$_POST["ctct_st_code"])
					echo "selected";
				echo ">";				
				echo $val;
				echo "</option>";
			}
		?>
	</select>&nbsp;
</td>
<td>Zip: <input type="text" name="ctct_addr_z" size="6" maxlength="10" value='<?php echo $_POST["ctct_addr_z"]; ?>' style="width: 50px" /></td>
</tr>
</table>
</div>

<!-- office not used for mid...yet //-->
<div class="span6" style="display:none">
<strong>Office Address:</strong>
<table>
<tr>
<td>Line 1:</td><td colspan="2"><input type="text" name="ctct_waddr_1" size="40" maxlength="63" value='<?php echo $_POST["ctct_waddr_1"]; ?>' /></td>
</tr>
<tr>
<td>Line 2:</td><td colspan="2"><input type="text" name="ctct_waddr_2" size="40" maxlength="63" value='<?php echo $_POST["ctct_waddr_2"]; ?>' /></td>
</tr>
<tr>
<td>City:</td><td colspan="2"><input type="text" name="ctct_waddr_c" size="40" maxlength="63" value='<?php echo $_POST["ctct_waddr_c"]; ?>' /></td>
</tr>
<tr>
<td>State:</td><td>
<select name="wctct_st_code" id="wctct_st_code">
	<?php
	
			/*foreach ($states as $key=>$val)
			{			
				echo "<option value='".$key."'";
				if($key==$_POST["wctct_st_code"])
					echo "selected";
				echo ">";				
				echo $val;
				echo "</option>";
			}*/
		?>
	</select>&nbsp;
</td>
<td>Zip: <input type="text" name="ctct_waddr_z" size="6" maxlength="10" value='<?php echo $_POST["ctct_waddr_z"]; ?>' style="width: 50px" /></td>
</tr>
</table>
</div>
</div>

<div class="row">
<div class="span2">
Phone (h):
</div>
<div class="span2">
<input type="text" name="ctct_hphone" size="18" maxlength="18" value="<?php echo $_POST["ctct_hphone"]; ?>" style="width: 100px">
</div>
<div class="span2">
Phone (w):
</div>
<div class="span2">
<input type="text" name="ctct_phone" size="18" maxlength="18" value="<?php echo $_POST["ctct_phone"]; ?>" style="width: 100px">
</div>
<div class="span2">
<b>Ext:</b> <input type="text" name="ctct_ext1" size="18" maxlength="18" value="<?php echo $_POST["ctct_ext1"]; ?>" style="width: 50px">
</div>
<div class="span2">
&nbsp;
</div>
</div>

<div class="row">
<div class="span2">
Fax (h):
</div>
<div class="span2">
<input type="text" name="ctct_hfax" size="18" maxlength="18" value="<?php echo $_POST["ctct_hfax"]; ?>" style="width: 100px">
</div>
<div class="span2">
Fax (w):
</div>
<div class="span2">
<input type="text" name="ctct_fax" size="18" maxlength="18" value="<?php echo $_POST["ctct_fax"]; ?>" style="width: 100px">
</div>
<div class="span2">
<b>Ext:</b> <input type="text" name="ctct_ext2" size="18" maxlength="18" value="<?php echo $_POST["ctct_ext2"]; ?>" style="width: 50px">
</div>
<div class="span2">
&nbsp;
</div>
</div>

<div class="row">
<div class="span2">
Cell phone:
</div>
<div class="span2">
<input type="text" name="ctct_cell" size="18" maxlength="18" value="<?php echo $_POST["ctct_cell"]; ?>" style="width: 100px">
</div>
<div class="span2">
Pager:
</div>
<div class="span2">
<input type="text" name="ctct_pager" size="18" maxlength="18" value="<?php echo $_POST["ctct_pager"]; ?>" style="width: 100px">
</div>
<div class="span2">
<b>PIN:</b> <input type="text" name="ctct_ext3" size="18" maxlength="18" value="<?php echo $_POST["ctct_ext3"]; ?>" style="width: 50px">
</div>
<div class="span2">
&nbsp;
</div>
</div>

<div class="row">
<div class="span2">
E-mail:
</div>
<div class="span4">
<input type="text" name="ctct_email" size="50" maxlength="50" value="<?php echo $_POST["ctct_email"]; ?>" >
</div>
<!--
<div class="span2">
Company Name:
</div>
<div class="span4">
<input type="text" name="ctct_company" size="18" maxlength="18" value="<?php //echo $_POST["ctct_company"]; ?>" >
</div>-->
</div>

<br/>


<hr/>

<h4>Personal Information</h4>

<div class="row">
<div class="span2">
Category:
</div>
<div class="span4">
<select  size="1" name="an_type0" class="cour" id="mdl-cats">
<?php
	//echo var_dump($specs);
	$nbsp = array();
	$nbsp[0] = "&nbsp;&nbsp;&nbsp;";
	$nbsp[1] = "&nbsp;&nbsp;";
	$nbsp[2] = "&nbsp;";
	$nbsp[3] = "";
	
			foreach ($specs as $key=>$val)
			{		//(RS("skill") = "--" and IsNull(RS0("ph_skill")) OR RS0("ph_skill")=RS("skill") OR RS("skill") = "  " and IsNull(RS0("ph_skill"))
				/*$code = $val["sp_code"].$nbsp[strlen($val["sp_code"])];
				echo "<option value='".$val["sp_code"]."|".$val["skill"]."'";
				//if(strtoupper($val["sp_code"])==strtoupper($_POST["ph_spec_main"]) && ($val["skill"]=="--" && ($ar["ph_skill"]==""||$ar["ph_skill"]==null) || $ar["ph_skill"]==$val["skill"] || $ar["ph_skill"] == "  " && ($ar["ph_skill"]==""||$ar["ph_skill"]==null) ))				
					//echo "selected";
				echo ">";				
				echo $code."&nbsp;".$val['spec'];
				echo "</option>";*/
				echo $key."-".$val."<br/>";
				echo "<option value='".$key."'";
				echo ">";
				echo $val;
				echo "</option>";
			}
?>
</select><br/>
Subspecialty: <select   name="an_type" class="phg-cour" id="mdl-spec">
<?php
	/*
	$nbsp = array();
	$nbsp[0] = "&nbsp;&nbsp;&nbsp;";
	$nbsp[1] = "&nbsp;&nbsp;";
	$nbsp[2] = "&nbsp;";
	$nbsp[3] = "";
	
			foreach ($specs as $key=>$val)
			{		//(RS("skill") = "--" and IsNull(RS0("ph_skill")) OR RS0("ph_skill")=RS("skill") OR RS("skill") = "  " and IsNull(RS0("ph_skill"))
				$code = $val["sp_code"].$nbsp[strlen($val["sp_code"])];
				echo "<option value='".$val["sp_code"]."|".$val["skill"]."'";
				//if(strtoupper($val["sp_code"])==strtoupper($_POST["ph_spec_main"]) && ($val["skill"]=="--" && ($ar["ph_skill"]==""||$ar["ph_skill"]==null) || $ar["ph_skill"]==$val["skill"] || $ar["ph_skill"] == "  " && ($ar["ph_skill"]==""||$ar["ph_skill"]==null) ))				
					//echo "selected";
				echo ">";				
				echo $code."&nbsp;".$val['spec'];
				echo "</option>";
			}*/
?>
</select><br/>
</div>
<div class="span2">
DOB: (YYYY-MM-DD)
</div>
<div class="span4">
<input type="text" name="an_DOB" size="18" maxlength="18" value="<?php //echo $_POST["ph_DOB"]; ?>" title="Enter a Date, or Month/Year, or just Year" >
</div>
</div>


<div class="row">
<div class="span2">
Gender:
</div>
<div class="span4">
<input  type="radio" value="1" <?php if($_POST["an_sex"]!=0) {echo "checked";} ?>  name="an_sex"> 
      Male&nbsp;
	  <input  type="radio" name="an_sex" <?php if($_POST["an_sex"]==0) {echo "checked";} ?> value="0"> Female
</div>
<div class="span2">
Visa/Citizenship: 
</div>
<div class="span4">
<select size="1" name="an_citizen" >
    <option  value="0" <?php if($_POST["an_citizen"]=="0") {echo "selected";} ?> >N/A</option>
    <option value="1" <?php if($_POST["an_citizen"]=="1") {echo "selected";} ?> >US Citizen</option>
    <option value="2" <?php if($_POST["an_citizen"]=="2") {echo "selected";} ?> >Perm. Res.</option>
    <option value="3" <?php if($_POST["an_citizen"]=="3") {echo "selected";} ?> >H visas</option>
    <option value="4" <?php if($_POST["an_citizen"]=="4") {echo "selected";} ?> >Other visas</option>
    <option value="5" <?php if($_POST["an_citizen"]=="5") {echo "selected";} ?> >None</option>
  </select>

</div>
</div>

<div class="row">
<div class="span2">
Languages:
</div>
<div class="span4">
<input  type="text" name="an_lang" size="30" maxlength="64" value="<?php echo $_POST["an_lang"]; ?>">
</div>
<div class="span2">
Experience:
</div>
<div class="span4">
<select size="1" name="an_experience" >
        <option value="0" <?php if($_POST["an_experience"]=="0") {echo "selected";} ?>>None</option>
        <option value="1" <?php if($_POST["an_experience"]=="1") {echo "selected";} ?> >Entry-level</option>
        <option value="2" <?php if($_POST["an_experience"]=="2") {echo "selected";} ?> >Mid-level</option>
        <option value="3" <?php if($_POST["an_experience"]=="3") {echo "selected";} ?> >Advanced</option>
        <option value="4" <?php if($_POST["an_experience"]=="4") {echo "selected";} ?> >Senior level</option>
      </select>
</div>
</div>

<div class="row">

<div class="span2">
Locum Tenens:
</div>
<div class="span4">
<input  type="radio" value="1" <?php if($_POST["an_locums"]!=0) {echo "checked";} ?>  name="an_locums"> Interested&nbsp;&nbsp;
<input  type="radio" value="0" <?php if($_POST["an_locums"]==0) {echo "checked";} ?> name="an_locums"> Not interested
</div>

<div class="span2">
<label>DEA License:</label>
</div>
<div class="span4">
<input type="radio" value="1" <?php if($_POST["an_dea"]!=0) {echo "checked";} ?> name="an_dea"> Yes
		<input name="an_dea" type="radio" value="0" <?php if($_POST["an_dea"]==0 || $_POST["an_dea"]=='') {echo "checked";} ?> > No <br/><br/>
</div>


</div>


<div class="row">
<div class="span2">
Board Certified:
</div>
<div class="span4">
<input type="radio" value="1" name="an_bc" <?php if($_POST["an_bc"]!=0) {echo "checked";} ?>> Yes
		<input name="an_bc" type="radio" value="0" <?php if($_POST["an_bc"]==0 || $_POST["an_bc"]=='') {echo "checked";} ?> > No
</div>

<div class="span2">
BC in States:
</div>
<div class="span4">
<input type="text" name="an_bc_state" size="30" maxlength="50" value="<?php echo $_POST["an_bc_state"]; ?>" title="Type in State codes, separated by commas, like this: GA,CA,VA" >
</div>
</div>

<div class="row">
<div class="span2">
Addtl. Certification:
</div>
<div class="span4">
<input type="text" name="an_certificates" size="30" maxlength="255" value="<?php echo $_POST["an_certificates"]; ?>" >

</div>
<div class="span2">
Licenses:
</div>
<div class="span4">
<input type="text" name="an_licenses" size="30" maxlength="127" title="Type in State codes, separated by commas, like this: GA,CA,VA" value="<?php echo $_POST["an_licenses"]; ?>">
</div>
</div>

<div class="row">
<div class="span2">
Pref State:
</div>
<div class="span4">
<input type="text" name="an_pref_states" size="30" maxlength="50" title="Type in State codes, separated by commas, like this: GA,CA,VA" value="<?php echo $_POST["an_pref_states"]; ?>">

</div>
<div class="span2">
Pref City:
</div>
<div class="span4">
<input type="text" name="an_pref_city" size="30" maxlength="50"  value="<?php echo $_POST["an_pref_city"]; ?>">
</div>
</div>

<hr/>

<div class="row">
<div class="span2">
Link to CV file:
</div>
<div class="span4">
<input  type="text" name="an_cv_url" value="<?php echo $_POST["an_cv_url"]; ?>" />
</div>

<div class="span2">
Avail Date:
</div>
<div class="span4">
<input type="text" name="ph_availtxt" id="ph_availtxt" class="datefld" value="<?php if($_POST["ph_avail"]!=""){echo date('m/d/Y', strtotime($_POST["ph_avail"]));} ?>" />
<input type="hidden" name="ph_avail" id="ph_avail" value="<?php echo $_POST["ph_avail"]; ?>">
</div>

</div>

<div class="row">
<div class="span2">
CV Date:
</div>
<div class="span4">
<input type="text" name="ph_cv_datetxt" id="ph_cv_datetxt" class="datefld" value="<?php if($_POST["ph_cv_date"]!=""){echo date('m/d/Y', strtotime($_POST["ph_cv_date"]));} ?>" />
<input type="hidden" name="ph_cv_date" id="ph_cv_date" value="<?php echo $_POST["ph_cv_date"]; ?>" />
</div>

</div>

<div class="row">
<div class="span2">
CV Text
</div>
<div class="span8">
<textarea  rows="3" name="an_cv_text" cols="35" style="width: 400px"><?php echo $_POST["an_cv_text"]; ?></textarea>
</div>
<div class="span2">

</div>

</div>



<div class="row">
<div class="span4">
<input type="submit" name="submitadd" value="Add" id="submitadd" class="btn-large btn"/>
<input type="button" name="canceladd" value="Cancel" id="canceladd" class="btn-large btn" />
</div>
<div class="span4">

</div>

<div class="span4">

</div>
</div>

<div class="row">
<br/>

<div class="hide" id="atb-div"><?php echo $atb ?></div>

</div>


<?php
echo $this->form()->closeTag();

    } else /* $phguser->access <= 1 */ { ?>
    <div class="alert alert-error">
        <h3>Access Denied</h3>
        <p>Database Administrative access required for this page</p>
    </div>
<?php
    } /* $phguser->access <= 1 */
/*$url = $this->url('resort', array('action'=>'physicians'));
$url2 = $this->url('resort', array('action'=>'mdes')); // . add / edit / del / get
$redir = $this->url('login');
$scrip = "phyInit(\"#phy-tbody\",\"#phy-pages\", \"$url\", \"$redir\", \"$url2\");\n";
$this->inlineScript()->appendScript($scrip, 'text/javascript');*/
//$scrip = "phyInit(\"#ctr-tbody\",\"#ctr-pages\", \"$url\", \"$redir\");\n";
//$this->inlineScript()->appendScript($scrip, 'text/javascript');

$url2 = $this->url('resort', array('action'=>'mdes')); // . add / edit / del / get
$url = $this->url('resort', array('action'=>'midlevels'));
$redir = $this->url('login');
$scrip = "mdlInit(\"#mdl-tbody\",\"#mdl-pages\", \"$url\", \"$redir\", $atc, \"$url2\");\n";
$this->inlineScript()->appendScript($scrip, 'text/javascript');


echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-mis'));
