<?php
// module/Pinnacle/view/pinnacle/midlevel/assessment.phtml:
// Contract Search

$title = 'Candidate Assessment Notes';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');

//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');
/*
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');*/

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<style>
#phystable { width: 70% }
#datetable, #spectable, #phystable, .historytable { border: 1px solid black }
#datetable td, #spectable td, .historytable td { border: 1px solid black }
#phystable td { border: 1px solid black; background-color: #ffffff; }
.tab { /*common class for tabs*/ margin-left: auto; margin-right: auto; }
.hiddendiv { display: none; }
#physician_pass_div { display: none; }
#sched_activity_div { display: none; }
.date { width: 110px; }
.time { width: 60px; }
.questions { width: 300px; }
</style>

<script>
function pageLoad() { //need to force calendar load            
			
			$( "#as_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#as_date"});			
			
}
function contractChange(){
//alert($("#ctr_id").val());
	//document.location = "assessm0.asp?ph_id=<%=Request("ph_id")%>&nut=<%=Request("nut")%>&ctr_id=" & ass_ctr.value
	document.location = "<?php echo $this->basePath(); ?>/midlevel/assessment/<?php echo $id; ?>?ctr_id="+$("#ctr_id").val();
}
</script>


<h1 ><?php echo $this->escapeHtml($title); ?></h1>
<br/>
<?php
    //$form->setAttribute('action', $this->url('resort', array('action'=>'midlevels')));
    //$form->get('submit')->setAttribute('type','button');
  
    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));

    echo $this->form()->openTag($form);
	//echo var_dump($ar);
		
	
?>


<p style="text-align:center; color: red"><?php echo $message; ?></p>

<input type="hidden" name="ctr_id" value="">
<input type="hidden" name="ph_id" value="<?php echo $id; ?>">
<input type="hidden" name="nut" value="1">

<input name="ph_ca_not" type="checkbox" id="ph_ca_not" <?php if($an_ca_not==1){ echo "checked";} ?> value="1"> 
		Candidate Assessment not required. <em>Don't put anything below if checked.</em>
		<br/><br/><br/>
		
<div class="row">
    
	
	 <div class="span8">
		<label><strong>Contract:</strong></label>
<select name="ctr_id" id="ctr_id" onchange="contractChange()" >
<option value="">--select contract--</option>
<?php
//echo var_dump($contracts);
foreach ($contracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'";
	if($_GET["ctr_id"]==$val['ctr_id'])
		echo "selected";
	echo ">";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>
<br/>
		<label>Interview Date</label>
		<input type="text" name="as_datetxt" id="as_datetxt" value="" class="date"/>
		<input type="hidden" name="as_date" id="as_date" value="<?php echo $ar["as_date"]; ?>"/>
	</div>
	

</div>

<div class="row">
    
	<div class="span4">
	<label>Relocation Motivation</label>
		<textarea rows="5"  name="as_motiv" cols="75"><?php echo $ar["as_motiv"]; ?></textarea>
	</div>
	<div class="span4">
	<label>Goals for New Opportunity</label>
		<textarea rows="5"  name="as_goals" cols="75"><?php echo $ar["as_goals"]; ?></textarea>
	</div>
</div>

<div class="row">    
	
</div>

<div class="row">
    
	<div class="span4">
	<label>Family</label>
		<textarea rows="5"  name="as_family" cols="75"><?php echo $ar["as_family"]; ?></textarea>
	</div>
	<div class="span4">
	<label>Hobbies, Free time Activities, etc.</label>
		<textarea rows="5"  name="as_hobby" cols="75"><?php echo $ar["as_hobby"]; ?></textarea>
	</div>
</div>

<div class="row">    
	
</div>

<div class="row">
    
	<div class="span8">
	<label>Items to Accomplish During Site Visit</label>
		<textarea rows="5"  name="as_items" cols="75"><?php echo $ar["as_items"]; ?></textarea>
	</div>
</div>


<br/>
<input type="submit" name="savebtn" value="Save" class="btn btn-large" />
<input type="submit" name="cancelbtn" value="Cancel" class="btn btn-large" />

<br/><br/>
<p>To return to a provider record, <a href="<?php echo $this->basePath(); ?>/midlevel/view/<?php echo $id; ?>">click here</a>.</p>	


<a href="<?php echo $this->basePath(); ?>/word_doc2.php?filename=Reports\ASSESSMENT FORM MM.DOCx&ctr_no=<?php echo $ar['ctr_no'];?>&ph_id=<?php echo $ar['ph_id'];?>&as_date=<?php echo $ar['as_date'];?>&as_motiv=<?php echo $ar['as_motiv'];?>&as_goals=<?php echo $ar['as_goals'];?>&as_family=<?php echo $ar['as_family'];?>&as_hobby=<?php echo $ar['as_hobby'];?>&as_items=<?php echo $ar['as_items'];?>&ctct_name=<?php echo $ar['ctct_name'];?>&ctct_title=<?php echo $ar['ctct_title'];?>" >Print Candidate Assessment</a>




<div style="clear:both">&nbsp;</div>
<?php
    echo $this->form()->closeTag();
?>






<script>
pageLoad();

</script>
<?php

echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
