<?php
// module/Pinnacle/view/pinnacle/midlevel/view.phtml:
// Midlevel

$title = 'Midlevel View';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');

//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');
/*
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');*/

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<style>
#phystable { width: 70% }
#datetable, #spectable, #phystable, .historytable { border: 1px solid black }
#datetable td, #spectable td, .historytable td { border: 1px solid black }
#phystable td { border: 1px solid black; background-color: #ffffff; }
.tab { /*common class for tabs*/ margin-left: auto; margin-right: auto; }
.hiddendiv { display: none; }
#physician_pass_div { display: none; }
#sched_activity_div { display: none; }
#pending_panel, #addsource_panel, #candass_panel, #pres_panel, #int_panel, #plac_panel, #replac_panel, #loc_pres_panel, #loc_pass_panel, #genctr_date_panel, #genctr_pop, #bill_panel, #ama_panel { display: none; }
.date { width: 110px; }
.time { width: 60px; }
#loc_pass_panel strong { font-size: 14px;  }
#loc_pass_panel { font-size: 11px; line-height: 11px; }
#loc_pass_panel input, #loc_pass_panel label { font-size: 11px; line-height: 11px; }
</style>
<script style="text/javascript">
function pageLoad() { //need to force calendar load            
			//alert('test');
			$( "#schedact_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#schedact_date"});
			$( "#pres_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#pres_date"});
			$( "#int_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#int_date"});
			$( "#loc_pres_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#loc_pres_date"});
			$( "#cdate_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#cdate_date"});
			$( "#addsource_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#addsource_date"});
			$( "#pend_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#pend_date"});
			//$('#schedact_timetxt').timepicker();//{ 'timeFormat': 'H:i' });
}

$(function() {

function loadSources(id)
 { 
	$.getJSON('<?php echo $this->basePath();?>/ajax/getSourceList/'+id+'', function(data) {
	var items = [];
	
	
	items = data["arr"];
	
	$.each(items, function (i, item) {
    $('#srctx').append($('<option>', { 
        value: item.src_name,
        text : item.src_name 
    }));
});
	//if(data["arr"].ctct_email!=null)
	//$("#contactemaillbl").html('<a href="mailto:'+data["arr"].ctct_email+'">'+data["arr"].ctct_email+'</a>');
	//$("#contactnotelbl").text(data["arr"].ctct_note);		
	});
	//$("#contact_holder").css('visibility','visible');
 }

 function switchPanel(obj)
{	
	$(".tab").addClass('hiddendiv');
	obj.toggleClass('hiddendiv');
}

$("#noteslink").click(function() {	
	switchPanel($("#notes-div"));
});
$("#cvlink").click(function() {	
	switchPanel($("#cv-div"));
});
$("#actionslink").click(function() {	
	switchPanel($("#actions-div"));
});
$("#sourcelink").click(function() {	
	switchPanel($("#source-div"));
});
$("#credentialslink").click(function() {	
	switchPanel($("#credentials-div"));
});

$("#physician_pass_link").click(function() {	
	openPhysicianPassPanel();
 });
 //close/cancel btn
 $("#mid_pass_cancel_btn").click(function() { $( "#physician_pass_div" ).dialog("close"); });
 $("#sched_cancel_btn").click(function() { $( "#sched_activity_div" ).dialog("close"); });
 $("#pres_cancel_btn").click(function() { $( "#pres_panel" ).dialog("close"); });
 $("#int_cancel_btn").click(function() { $( "#int_panel" ).dialog("close"); });
 $("#plac_cancel_btn").click(function() { $( "#plac_panel" ).dialog("close"); });
 $("#replac_cancel_btn").click(function() { $( "#replac_panel" ).dialog("close"); });
 $("#loc_pass_cancel_btn").click(function() { $( "#loc_pass_panel" ).dialog("close"); });
 $("#bill_cancel_btn").click(function() { $( "#bill_panel" ).dialog("close"); });
 $("#ama_cancel_btn").click(function() { $( "#ama_panel" ).dialog("close"); });
  $("#candass_cancel_btn").click(function() { $( "#candass_panel" ).dialog("close"); });
 $("#pend_cancel_btn").click(function() { $( "#pending_panel" ).dialog("close"); }); 

$("#schedulelink").click(function() {	
	openSchedulePanel();
 }); 
 
 
$("#present_link").click(function() {	
	openPresentPanel();
 }); 
 
 $("#interview_link").click(function() {	
	openInterviewPanel();
 });
 
  $("#placement_link").click(function() {	
	openPlacementPanel();
 });
 
 $("#replacement_link").click(function() {	
	openReplacementPanel();
 });
 
 $("#locum_present_link").click(function() {	
	openLocumsPresentPanel();
 });
 
  $("#locum_pass_link").click(function() {	
	openLocumsPassPanel();
 });
 
 $("#add_record_link").click(function() {	
	loadSources($("#addsource_ctr_id").val());
	openSourcePanel();
 });
 
 $("#refcheckreq").click(function() {	
	openBillingPanel();
 });

 $("#amacheckreq").click(function() {	
	openAMAPanel();
 }); 
 
 $("#candass_link").click(function() {	
	openCandassPanel();
 });
 
 $("#pend_pop_link").click(function() {	
	openPendingPanel();
 });
 
 //date links for credentials
 $("#ref_ref0").click(function() {	
	$( "#ref_row" ).show();
	$( "#ama_row" ).hide();
	$( "#ref_date_submit_btn" ).show();
	$( "#ama_date_submit_btn" ).hide();
	$( "#preint_date_submit_btn" ).hide();
	$( "#cand_ass_date_submit_btn" ).hide();
	$( "#packet_date_submit_btn" ).hide();
	openCredDatePanel();
 });
  $("#ref_ama0").click(function() {	
	$( "#ref_row" ).hide();
	$( "#ama_row" ).show();
	$( "#ref_date_submit_btn" ).hide();
	$( "#ama_date_submit_btn" ).show();
	$( "#preint_date_submit_btn" ).hide();
	$( "#cand_ass_date_submit_btn" ).hide();
	$( "#packet_date_submit_btn" ).hide();
	openCredDatePanel();
 });
  $("#ref_prei0").click(function() {
	$( "#ref_row" ).hide();
	$( "#ama_row" ).hide();
	$( "#ref_date_submit_btn" ).hide();
	$( "#ama_date_submit_btn" ).hide();
	$( "#preint_date_submit_btn" ).show();
	$( "#cand_ass_date_submit_btn" ).hide();
	$( "#packet_date_submit_btn" ).hide();
	openCredDatePanel();
 });
  $("#ref_ref1").click(function() {	
	$( "#ref_row" ).hide();
	$( "#ama_row" ).hide();
	$( "#ref_date_submit_btn" ).hide();
	$( "#ama_date_submit_btn" ).hide();
	$( "#preint_date_submit_btn" ).hide();
	$( "#cand_ass_date_submit_btn" ).hide();
	$( "#packet_date_submit_btn" ).show();
	openCredDatePanel();
 });
 $("#genctr_date_cancel_btn").click(function() { $( "#genctr_date_panel" ).dialog("close"); });
 
 //<input type="submit" value="Submit" id="ref_date_submit_btn" name="ref_date_submit_btn" />
//<input type="submit" value="Submit" id="ama_date_submit_btn" name="ama_date_submit_btn" />
//<input type="submit" value="Submit" id="preint_date_submit_btn" name="preint_date_submit_btn" />
//<input type="submit" value="Submit" id="cand_ass_date_submit_btn" name="cand_ass_date_submit_btn" />
//<input type="submit" value="Submit" id="packet_date_submit_btn" name="packet_date_submit_btn" />
//end links
 
});

function openPhysicianPassPanel(){
$( "#physician_pass_div" ).dialog({
height: 370,
width: 640,
modal: true
});
}

function openSchedulePanel(){
$( "#sched_activity_div" ).dialog({
height: 520,
width: 440,
modal: true
});
}

function openPresentPanel(){
$( "#pres_panel" ).dialog({
height: 420,
width: 440,
modal: true
});
}

function openInterviewPanel(){
$( "#int_panel" ).dialog({
height: 320,
width: 440,
modal: true
});
}

function openPlacementPanel(){
$( "#plac_panel" ).dialog({
height: 320,
width: 440,
modal: true
});
}

function openReplacementPanel(){
$( "#replac_panel" ).dialog({
height: 320,
width: 440,
modal: true
});
}

function openLocumsPresentPanel(){
$( "#loc_pres_panel" ).dialog({
height: 320,
width: 440,
modal: true
});
} 

function openLocumsPassPanel(){
$( "#loc_pass_panel" ).dialog({
height: 780,
width: 720,
modal: true
});
}

function openCredDatePanel(){
$( "#genctr_date_panel" ).dialog({
height: 280,
width: 440,
modal: true
});
} 

function openCredPanel(){
$( "#genctr_pop" ).dialog({
height: 200,
width: 440,
modal: true
});
}

function openSourcePanel(){
$( "#addsource_panel" ).dialog({
height: 600,
width: 440,
modal: true
});
}

function openBillingPanel(){
$( "#bill_panel" ).dialog({
height: 320,
width: 440,
modal: true
});
}

function openAMAPanel(){
$( "#ama_panel" ).dialog({
height: 320,
width: 440,
modal: true
});
}

function openCandassPanel(){
$( "#candass_panel" ).dialog({
height: 240,
width: 340,
modal: true
});
}

function openPendingPanel(){
$( "#pending_panel" ).dialog({
height: 320,
width: 340,
modal: true
});
} 

</script>

<h1 style="display: none"><?php //echo $this->escapeHtml($title); ?></h1>
<br/>
<?php
    //$form->setAttribute('action', $this->url('resort', array('action'=>'midlevels')));
    //$form->get('submit')->setAttribute('type','button');
    if( strpos($phguser->dept,'R') !== false ) {
        //$form->get('ph_recruiter')->setValue($phguser->uid);
        //$form->get('ph_status')->setValue(1);
    }
    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));

    echo $this->form()->openTag($form);
	//echo var_dump($ar);
?>
<div class="row">
    <div class="span4">
        <a href="<?php echo $this->basePath(); ?>/midlevel/add">Add a Midlevel</a>
    </div>
    <div class="span4">
        <a href="">Export</a>
    </div>
    <div class="span4">
        <a href="<?php echo $this->basePath(); ?>/midlevel/edit/<?php echo $ar["an_id"]; ?>">Edit</a>
    </div>
</div>
<div class="row">
    <div class="span12">
		<div style="float: right">
		<table id="spectable">
			<tr>
				<td>Cat</td>
				<td>BC</td>
				<td>State</td>
			</tr>
			<tr>
				<td><span title="<?php echo $ar["at_abbr"]; ?>"><?php echo $ar["at_abbr"]; ?></td>
				<td><?php if($ar["an_bc"]==""||$ar["an_bc"]==0) { echo "No"; } else  { echo "BC"; }?></span></td>
				<td><?php echo $ar["an_bc_state"]; ?>&nbsp;</td>				
			</tr>
			<tr><td>DEA</td><td colspan="2"><?php if($ar["an_dea"]==""||$ar["an_dea"]==0) { echo "Not licensed"; } else  { echo "Licensed"; }?></td></tr>			 
		</table><br/>
		
		<table id="datetable">
			<tr>
				<td></td>
				<td>Date</td>				
			</tr>
			<!--<tr>
				<td>First Inquiry:</td>
				<td><?php //if($ar["ph_1st_inq"]!="") { echo date('m-d-Y', strtotime($ar["ph_1st_inq"])); }?></td>				
			</tr>-->
			<tr>
				<td>Available:</td>
				<td><?php if($ar["an_avail"]!="") { echo date('m-d-Y', strtotime($ar["an_avail"])); } ?></td>				
			</tr>
			<!--<tr>
				<td>CV Date:</td>
				<td><?php //if($ar["ph_cv_date"]!="") { echo date('m-d-Y', strtotime($ar["ph_cv_date"])); } ?></td>				
			</tr>
			<tr>
				<td>Phone Interview:</td>
				<td><?php //if($ar["ph_phone_date"]!="") { echo date('m-d-Y', strtotime($ar["ph_phone_date"])); } ?></td>				
			</tr>
			<tr>
				<td>Contract Date:</td>
				<td><?php //if($ar["ph_ctr_date"]!="") { echo date('m-d-Y', strtotime($ar["ph_ctr_date"])); } ?></td>				
			</tr>
			<tr>
				<td>Start Date:</td>
				<td><?php //if($ar["ph_start_date"]!="") { echo date('m-d-Y', strtotime($ar["ph_start_date"])); } ?></td>				
			</tr>-->
		</table>
		
		</div>
		
		<div>
        <table id="phystable">
			<tr>
				<td><strong>ID #:</strong></td>
				<td><?php echo $ar["an_id"]; ?></td>
				<td><strong>Status:</strong></td>
				<td><?php echo $ar["st_name"]; ?><?php //echo $ar["ph_status"]; ?></td>
				<td><strong>Category:</strong></td>
				<td><?php echo $ar["at_name"]; ?></td>
			</tr>
			<tr>
				<td><strong>Name:</strong></td>
				<td colspan="2"><?php echo $ar["ctct_name"]; ?></td>
				<td><?php echo $ar["ctct_title"]; ?></td>
				
				<td><strong>Licenses:</strong></td>
				<td><?php echo $ar["an_licenses"]; ?></td>
			</tr>
			<tr>
				<td><strong>City, State:</strong></td>
				<td><?php echo $ar["ctct_addr_c"].", ".$ar["st_code"]; ?></td>
				<td><strong>Zip:</strong></td>
				<td><?php echo $ar["ctct_addr_z"]; ?></td>
				<td><strong>Pref Location:</strong></td>
				<td><?php echo $ar["reg_name"]; ?></td>
			</tr>
			<tr>
				<td><strong>Gender:</strong></td>
				<td><?php if($ar["an_sex"]==1){ echo "Male"; } else { echo "Female"; } ?></td>
				<td><strong>DOB:</strong></td>
				<td><?php echo $ar["an_DOB"]; ?></td>
				<td><strong>Languages:</strong></td>
				<td><?php echo $ar["an_lang"]; ?></td>
			</tr>
			<tr>
				<td><strong>Home #:</strong></td>
				<td><strong>Work #:</strong></td>
				<td><strong>Cell #:</strong></td>
				<td><strong>Fax #:</strong></td>
				<td><strong>Experience:</strong></td>				
				<td>
				<?php 
				switch($ar['an_experience'])
				{
					case 4:
					echo "Senior level";
					break;
					case 3:
					echo "Advanced";
					break;
					case 2:
					echo "Middle level";
					break;
					case 1:
					echo "Entry level";
					break;
					default:
					echo "Unknown";
					break;
				}
				 ?></td>
			</tr>
			<tr>
				<td><a href="http://db.phg.com/pinncopy/call_test.asp?phone=<?php echo $ar['ctct_hphone']; ?>" target="_blank"><?php echo $ar["ctct_hphone"]; ?></a></td>
				<td><a href="http://db.phg.com/pinncopy/call_test.asp?phone=<?php echo $ar['ctct_phone']; ?>" target="_blank"><?php echo $ar["ctct_phone"]; ?></a><?php echo $ar["ctct_ext1"]; ?></td>
				<td><a href="http://db.phg.com/pinncopy/call_test.asp?phone=<?php echo $ar['ctct_cell']; ?>" target="_blank"><?php echo $ar["ctct_cell"]; ?></a></td>
				<td><?php echo $ar["ctct_hfax"]; ?><?php echo $ar["ctct_fax"]; ?></td>
				<td><strong>Certificates :</strong></td>
				<td><?php echo $ar["an_certificates"]; ?></td>
			</tr>
			<tr>
				<td><strong>Email :</strong></td>
				<td colspan="2"><a href="mailto:<?php echo $ar["ctct_email"]; ?>"><?php echo $ar["ctct_email"]; ?></a></td>
				<td><strong>Pager :</strong></td>
				<td><?php echo $ar["ctct_pager"]; ?></td>				
				<td><strong>PIN :</strong><?php echo $ar["ctct_ext3"]; ?></td>
			</tr>
			
			<tr>
				<td><strong>Protected Until:</strong></td>
				<td><?php echo $ar["an_prot_date"]; ?> <?php echo $ar["emp_uname"]; ?></td>
				<td colspan="2"><strong>AMG/IMG/CAN/J1/H1B:</strong> <?php echo $ar["an_citizen"]; ?></td>				
				<td><strong>Modified :</strong></td>
				<td><?php echo $ar["an_date_mod"]; ?> by <?php echo $ar["an_user_mod"]; ?></td>
			</tr>
			<tr>
			<td ><strong>Visa status:</strong></td>
<td>
				<?php 
				switch($ar['an_citizen'])
				{
					case 5:
					echo "No visa";
					break;
					case 4:
					echo "Other visa";
					break;
					case 3:
					echo "H visa";
					break;
					case 2:
					echo "Perm. Res.";
					break;
					case 1:
					echo "US Citizen";
					break;
					default:
					echo "Unknown";
					break;
				}
				 ?></td><td colspan="4">&nbsp;</td></tr>
		</table>
		<?php 
		$srs = rtrim($_GET["srs"], ',');
		if($srs!='')
		{
			$ids;
			$i;
			$j;
			$idup;
			$iddown;
			
			$ids = explode(",", $srs);
			//echo count($ids);
			//echo $srs;
			//echo var_dump($ids);
			$j=count($ids)+1;
			for($i=0;$i<=count($ids);$i++)
			{
				if($ids[$i]==$ar["an_id"])
					$j=$i;	//echo $ids[$i];
			}			
			//echo $j;
			//if($j==0 || $j=='')
				//$j=1;
			if($j>0)			
				echo '<a href="'.$this->basePath().'/midlevel/view/'.$ids[$j-1].'?srs='.$srs.'"><img src="/public/img/images/ARW01LT.png" style="border:0px" />&nbsp;Previous</a>&nbsp;&nbsp;&nbsp;&nbsp;';
			//echo "HERE";
			if($j<count($ids)-1)
				echo '<a href="'.$this->basePath().'/midlevel/view/'.$ids[$j+1].'?srs='.$srs.'">Next&nbsp;<img src="/public/img/images/ARW01RT.png" style="border:0px" /></a>'; //next
		}
		?>
		</div>		
    </div>
    
</div>

<p style="text-align:center; color: red"><?php echo $message; ?></p>



<hr/>
<p>
<a href="#" id="noteslink" >Notes</a>&nbsp;
<a href="#" id="cvlink" >CV Information</a>&nbsp;
<a href="#" id="actionslink" >Actions</a>&nbsp;
<a href="#" id="sourcelink" >Source</a>&nbsp;
<a href="#" id="credentialslink" >Credentials</a>&nbsp;
<a href="#" id="schedulelink" style="float:right">Schedule an Activity</a>
</p>

<!--NOTES BOX //-->
<div id="notes-div" class="tab" >
<h4>NOTES</h4>
<div style="float: left; width: 90%">
<form  method="post">
<input type="hidden" id="an_id" value="<?php echo $ar['an_id']; ?>" />
<input type="hidden" name="ref_id" value='<?php echo $ar['an_id']; ?>' />
<input type="hidden" name="note_type" value="15"><input type="hidden" name="reserv" value="0"/>
<label>Enter Comment:</label>
<textarea name="comments" id="commenttxt" style="width: 60%"></textarea><br/>
<input type="submit" name="commentsubmit" id="commentsubmit" value="Add Comment" />
</form>
<hr/>
<table>
<?php
			foreach ($comments as $row2=>$ar2)
			{								
				echo "<tr><td style='vertical-align:top;padding: 10px;'>".$ar2['note_user']."</td><td style='vertical-align:top; padding: 10px;'>".$ar2['note_text']."</td><td style='vertical-align:top;padding: 10px;'>".$ar2['note_dt']."</td></tr>";
			}
?>
</table>
</div>

</div>
<!--END NOTES BOX //-->

<!--CV BOX //-->
<div id="cv-div" class="tab hiddendiv" >
<h4>CV Information</h4>

<table>
<tr>
<td><strong>CV Network Link:</strong></td>
<td><a href="<?php echo $ar["an_cv_url"]; ?>"><?php echo $ar["an_cv_url"]; ?></a></td>
</tr>
<tr>
<td><strong>CV Web Link:</strong></td>
<td><a href="<?php echo $this->basePath(); ?>/download_file.php?id=<?php echo $ar["cv_id"]; ?>"><?php echo $ar["filename"]; ?></a></td>
</tr>
<tr>
<td><strong>CV Text:</strong></td>
<td><?php echo $ar["an_cv_text"]; ?></td>
</tr>
<tr>
<td><strong>Upload:</strong></td>
<td><button  onclick='window.open("<?php echo $this->basePath();?>/upload.php?an_id=<?php echo $ar["an_id"]; ?>","myWindow","width=420,height=270");return false;' >Upload a CV</button></td>
</tr>
</table>
</div>
<!--END CV BOX //-->

<!--ACTIONS BOX //-->
<div id="actions-div" class="tab hiddendiv" >
<h4>Actions </h4>



<p><a href="#" id="physician_pass_link" onclick="">Midlevel Pass</a></p>
<!--<p><a href="#" onclick="">PhysicianCareer Pass</a></p>-->
<p><a href="#" id="present_link" onclick="">Present</a></p>
<p><a href="#" id="interview_link" onclick="">Interview</a></p>
<p><a href="#" id="pend_pop_link" >Pending</a></p>
<p><a href="#" id="placement_link" onclick="">Placement</a></p>
<p><a href="#" id="replacement_link" onclick="">Replacement</a></p>
<p><a href="#" id="locum_present_link" onclick="">Locum Tenens Present</a></p>
<!--<p><a href="#" onclick="">Pay Rates</a></p>-->
<p><a href="#" id="locum_pass_link" onclick="">Pass to Locums</a></p>

<h4>History</h4>

<table style="border: 1px solid " class="historytable">
<tr><th>Facility</th><th>Contract</th><th>Date</th><th>Status</th><th>Recruiter</th><th>Cancelled</th></tr>
<?php
foreach ($history as $r2=>$h2)
			{
?>
<tr>
  <td><a href="<?php echo $this->basePath(); ?>/client/view/<?php echo $h2["cli_id"]; ?>"><?php echo $h2["ctct_name"]; ?></a></td>
  <td><a href="<?php echo $this->basePath(); ?>/contract/view/<?php echo $h2["ctr_id"]; ?>"><?php echo $h2["ctr_no"]; ?></a></td>
  <td><?php echo $h2["pipl_date"]; ?></td>
  <td><?php echo $h2["pist_name"]; ?></td>
  <td><?php echo $h2["emp_uname"]; ?></td>
  <td>
  <?php
	if($h2["pipl_status"]==4 || $h2["pipl_status"]==5)
		echo '<a href="'.$this->basePath().'/contract/ctrchange?pipl_id='.$h2["pipl_id"].'&ctr_id='.$h2["ctr_id"].'&type=5&action=writeoff">'."Write Off</a>&nbsp;";
	elseif($h2["pipl_status"]==3 && $h2["pipl_cancel"]!=1)
		echo '<a href="?id='.$h2["pipl_id"].'&action=cancel">Cancel</a>&nbsp;';
	elseif($h2["pipl_cancel"]!=1)
		echo '<a href="?id='.$h2["pipl_id"].'&action=cancel">Cancel</a>&nbsp;';
	
	if($h2["pipl_cancel"]==1)
		echo "&nbsp;Cancelled";
	echo $h2["pipl_status"];
  ?>
  
  </td>
</tr>
<?php
}
?>
</table>


<h3>Passes:</h3>
<table border=1 cellpadding=2 cellspacing=0 class="nobg">
<thead>
 <tr><td>Date</td><td>From</td><td>To</td></tr>
<?php
foreach ($passes as $p2=>$v2)
{ 

echo'<tr>
  <td>'.$v2["pp_date"].'</td><td>'.$v2["rec_from"].'</td>
  <td>'.$v2["rec_to"].'</td>
</tr>';

}
?>
</table>
</div>
<!--END ACTIONS BOX //-->

<!--SOURCE BOX //-->
<div id="source-div" class="tab hiddendiv" >
<h4>Source </h4>

<a href="#" id="add_record_link">Add a record</a>

<br/><br/>
<?php if(count($sources2)>0) { ?>
<table border="1" cellspacing="1" class="nobg">
<TR>
<TD ALIGN="center"><B>Contract#</B></TD>
<TD ALIGN="center"><B>Source:</B></TD>
<TD ALIGN="center"><B>Recruiter:</B></TD>
<TD ALIGN="center"><B>Date Received:</B></TD>
</TR>
<?php } ?>
<?php
//echo var_dump($sources2);
foreach ($sources2 as $key=>$val)
{
	echo "<tr><td><a href='".$this->basePath()."/contract/view/".$val['ctr_id']."'>".$val['ctr_no']."</a></td><td>".$val['nsr_source']." ".$val['nsr_dm_code']."</td><td>".$val['emp_uname']."</td><td>".$val['nsr_date']."</td>";				
					
}
?>
</table>
</div>
<!--END SOURCE BOX //-->

<!--CREDENTIALS BOX //-->
<div id="credentials-div" class="tab hiddendiv" >
<h4>Credentials </h4>

<table style="width: 80%; border: 1px solid;">
<tr>
<td>Reference Request Submitted</td>
<td><a id="ref_ref0" class="fakea">
<?php 

   
   if($ar["an_ref_client"])
	echo "Client";
   elseif($ar["an_ref_recr"])
	echo "R.Hold";
   elseif($ar["an_ref_hold"])
	echo "C.Hold";
   elseif($ar["an_ref_submit"]=='')
	echo "Enter";
   else
	echo $ar["an_ref_submit"];
	
?></a>
</td>
<td><a class="fakea" id="refcheckreq">Billing Form</a></td>
</tr>
<tr>
<td>AMA Request Submitted</td>
<td><a id="ref_ama0" class="fakea">
<?php 
  
   if($ar["an_ama_client"])
	echo "Client";
   elseif($ar["an_ama_submit"]=='')	
	echo "Enter";
   else
	echo $ar["an_ama_submit"];	
?></a>
</td>
<td><a class="fakea" id="amacheckreq">Request an AMA Check</a></td>
</tr>
<tr>
<td>Pre-Interview Form Received</td>
<td><a id="ref_prei0" class="fakea">
<?php   
   if($ar["an_preint_got"]=='')	
	echo "Enter";
   else
	echo $ar["an_preint_got"];	
?>
</a></td>
<td><a class="fakea" id="phquest2">Send Physician Questionnaire email</a></td>
</tr>
<tr>
<td>Candidate Assessment</td>
<td>
<?php   
   if($ar["an_ca_not"])	
	echo "NA";
   else
	echo $ar["an_assesm"];	
?>
</td>
<td><a href="<?php echo $this->basePath(); ?>/midlevel/assessment/<?php echo $ar['an_id']; ?>">Candidate Assessment Notes</a></td>
</tr>
<tr>
<td>Packet Completed</td>
<td>
<a id="ref_ref1" class="fakea">
<?php   
   if($ar["an_completed"]=='')	
	echo "Enter";
   else
	echo $ar["an_completed"];	
?>
</a>
</td>
<td><a href="#" id="candass_link">Candidate Assessment Packet</a></td>
</tr>


</table>

Send Post-Interview TQC Questionnaire


</div>
<!--END CREDENTIALS BOX //-->


<!-- credentials panel genctr_pop//-->
<div id="genctr_pop" class="p0pup">
<form name="pres_form" method="post" action="<?php echo $this->basePath(); ?>/midlevel/assessment/<?php echo $ar["an_id"]; ?>" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="pres_status" value="2">
<input type="hidden" name="an_name" value="<?php echo $ar["ctct_name"]; ?>">
<input type="hidden" name="act_ret" value="15">


<label><strong>Contract:</strong></label>
<select name="genctr_ctr_id" >
<?php
//echo var_dump($contracts);
foreach ($contracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>

<br/><br/>
<input type="submit" value="Submit" id="genctr_submit_btn" name="genctr_submit_btn" />
<input type="button" value="Cancel" id="genctr_cancel_btn" />
</form>
</div>
<!-- credentials panel //-->

<!-- credentials date panel //-->
<div id="genctr_date_panel" class="p0pup">
<form name="genctr_date_form" method="post" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="pres_status" value="2">
<input type="hidden" name="an_name" value="<?php echo $ar["ctct_name"]; ?>">
<input type="hidden" name="act_ret" value="15">

<label><strong>Date:</strong></label>

<input type="text" name="cdate_datetxt" id="cdate_datetxt" value="" class="date"/>
<input type="hidden" name="cdate_date" id="cdate_date" value=""/>

<div id="ref_row" style="display:none">
<input type="checkbox" <?php if($ar["an_ref_client"]){ echo "checked"; } ?> value="1" name="client_tmp" id="client_fld">
  Client does Ref. Check<br>
    <input type="checkbox" <?php if($ar["an_ref_recr"]){ echo "checked"; } ?> value="1" name="client2_tmp" id="client2_fld">
  Recruiter Hold<br>
    <input type="checkbox" <?php if($ar["an_ref_hold"]){ echo "checked"; } ?> value="1" name="client4_tmp" id="client4_fld">
  Candidate Hold
</div>
<div id="ama_row" style="display:none">
  <input type="checkbox" <?php if($ar["an_ama_client"]){ echo "checked"; } ?> value="1" name="client3_tmp" id="client3_fld">
  Client does AMA Check
</div>

<br/><br/>
<input type="submit" value="Submit" id="ref_date_submit_btn" name="ref_date_submit_btn" />
<input type="submit" value="Submit" id="ama_date_submit_btn" name="ama_date_submit_btn" />
<input type="submit" value="Submit" id="preint_date_submit_btn" name="preint_date_submit_btn" />
<input type="submit" value="Submit" id="cand_ass_date_submit_btn" name="cand_ass_date_submit_btn" />
<input type="submit" value="Submit" id="packet_date_submit_btn" name="packet_date_submit_btn" />


<input type="button" value="Cancel" id="genctr_date_cancel_btn" />
</form>
</div>
<!-- credentials date panel //-->



<div style="clear:both">&nbsp;</div>
<?php
    echo $this->form()->closeTag();
?>
<div id="physician_pass_div" class="p0pup" style="">
<strong>Midlevel Pass</strong><br/><br/>
<form name="pass_form" method="POST" action="">
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="an_ct" value="<?php echo $ar["an_ctct_id"]; ?>">
<input type="hidden" name="an_tx" value="<?php echo $ar["ctct_name"]; ?>">
<input type="hidden" name="act_ret" value="15">
<input type="hidden" name="passt" value="PHG">
<strong>Pass to:</strong>
<select name="to[]" size="3" multiple="multiple">
<?php
			foreach ($rec as $key=>$val)
			{
				echo "<option value='".$key."'>";				
				echo $val;
				echo "</option>";
			}
		?>
</select>
<p>Hold the &lt;Ctrl&gt; button to select multiple recruiters</p>
<strong>Source:</strong>
<select name="pass_source" size="1" >
<?php
			foreach ($sources as $key=>$val)
			{
				echo "<option value='".$val['src_id']."'>";				
				echo $val['src_name'];
				echo "</option>";
				
			}
		?>
</select>
<?php //echo $var_dump($sources); ?>
<br/>

<input type="submit" value="Submit" id="mid_pass_submit_btn" name="mid_pass_submit_btn" />
<input type="button" value="Cancel" id="mid_pass_cancel_btn" />
</form>
</div>

<!-- present panel //-->
<div id="pres_panel" class="p0pup">
<form name="pres_form" method="post" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="pres_status" value="2">
<input type="hidden" name="an_name" value="<?php echo $ar["ctct_name"]; ?>">
<input type="hidden" name="act_ret" value="15">
<!--<input type="hidden" name="addon" value="see below">-->
<strong>Schedule Present</strong><br/><br/>

<label><strong>Contract:</strong></label>
<select name="pres_ctr_id" >
<?php
//echo var_dump($contracts);
foreach ($contracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>
<label><strong>Present Date:</strong></label>

<input type="text" name="pres_datetxt" id="pres_datetxt" value="" class="date"/>
<input type="hidden" name="pres_date" id="pres_date" value=""/>

<label><strong>Do you have a CV?</strong></label><input name="addon" type="radio" id="presycv" value="YES" /> Yes
&nbsp; <input name="addon" id="presnocv" type="radio" value="NO" /> No

<br/><br/>
<input type="submit" value="Submit" id="pres_submit_btn" name="pres_submit_btn" />
<input type="button" value="Cancel" id="pres_cancel_btn" />
</form>
</div>
<!-- present panel //-->

<!-- interview panel //-->
<div id="int_panel" class="p0pup">
<form name="int_form" method="post" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="int_status" value="3">
<input type="hidden" name="an_name" value="<?php echo $ar["ctct_name"]; ?>">
<input type="hidden" name="act_ret" value="15">
<!--<input type="hidden" name="addon" value="see below">-->
<strong>Schedule Interview</strong><br/><br/>

<label><strong>Contract:</strong></label>
<select name="int_ctr_id" >
<?php
//echo var_dump($contracts);
foreach ($contracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>
<label><strong>Interview Date:</strong></label>

<input type="text" name="int_datetxt" id="int_datetxt" value="" class="date"/>
<input type="hidden" name="int_date" id="int_date" value=""/>

<br/><br/>
<input type="submit" value="Submit" id="int_submit_btn" name="int_submit_btn" />
<input type="button" value="Cancel" id="int_cancel_btn" />
</form>
</div>
<!-- interview panel //-->


<!-- placement panel //-->
<div id="plac_panel" class="p0pup">
<form name="plac_form" method="post" action="<?php echo $this->basePath(); ?>/midlevel/placement/<?php echo $ar["an_id"]; ?>" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="plac_status" value="3">
<input type="hidden" name="an_name" value="<?php echo $ar["ctct_name"]; ?>">
<input type="hidden" name="re" value="0">
<input type="hidden" name="n" value="<?php echo $_GET["n"]; ?>">
<input type="hidden" name="srs" value="<?php echo $_GET["srs"]; ?>">
<input type="hidden" name="act_ret" value="15">
<strong>Placement</strong><br/><br/>

<label><strong>Contract:</strong></label>
<select name="plac_ctr_id" >
<?php
//echo var_dump($contracts);
foreach ($contracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>

<br/><br/>
<input type="submit" value="Submit" id="plac_submit_btn" name="plac_submit_btn" />
<input type="button" value="Cancel" id="plac_cancel_btn" />
</form>
</div>
<!-- placement panel //-->


<!-- replacement panel (same as above?)//-->
<div id="replac_panel" class="p0pup">
<form name="replac_form" method="post" action="<?php echo $this->basePath(); ?>/midlevel/placement/<?php echo $ar["an_id"]; ?>" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="plac_status" value="3">
<input type="hidden" name="an_name" value="<?php echo $ar["ctct_name"]; ?>">
<input type="hidden" name="re" value="0">
<input type="hidden" name="n" value="<?php echo $_GET["n"]; ?>">
<input type="hidden" name="srs" value="<?php echo $_GET["srs"]; ?>">
<input type="hidden" name="act_ret" value="15">
<strong>Replacement</strong><br/><br/>

<label><strong>Contract:</strong></label>
<select name="plac_ctr_id" >
<?php
//echo var_dump($contracts);
foreach ($contracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>

<br/><br/>
<input type="submit" value="Submit" id="replac_submit_btn" name="replac_submit_btn" />
<input type="button" value="Cancel" id="replac_cancel_btn" />
</form>
</div>
<!-- replacement panel //-->



<!-- locums present panel //-->
<div id="loc_pres_panel" class="p0pup">
<form name="loc_pres_form" method="post" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="pres_status" value="2">
<input type="hidden" name="an_name" value="<?php echo $ar["ctct_name"]; ?>">

<!--<input type="hidden" name="addon" value="see below">-->
<strong>Schedule Present</strong><br/><br/>

<label><strong>Contract:</strong></label>
<select name="pres_ctr_id" >
<?php
echo var_dump($ltcontracts);
foreach ($ltcontracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>
<label><strong>Present Date:</strong></label>

<input type="text" name="loc_pres_datetxt" id="loc_pres_datetxt" value="" class="date"/>
<input type="hidden" name="pres_date" id="loc_pres_date" value=""/>

<br/><br/>
<input type="submit" value="Submit" id="loc_pres_submit_btn" name="loc_pres_submit_btn" />
<input type="button" value="Cancel" id="loc_pres_cancel_btn" />
</form>
</div>
<!-- locums present panel //-->


<!-- billing panel //-->
<div id="bill_panel" class="p0pup">
<form name="bill_form" method="get" action="<?php echo $this->basePath(); ?>/midlevel/refbill" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<br/><br/>

<label><strong>Contract:</strong></label>
<select name="ctr_id" >
<?php
//echo var_dump($contracts);
foreach ($contracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>

<br/><br/>
<input type="submit" value="Submit" id="bill_submit_btn" name="bill_submit_btn" />
<input type="button" value="Cancel" id="bill_cancel_btn" />
</form>
</div>
<!-- billing panel //-->

<!-- amacheck panel //-->
<div id="ama_panel" class="p0pup">
<form name="ama_form" method="get" action="<?php echo $this->basePath(); ?>/midlevel/amacheck" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<br/><br/>

<label><strong>Contract:</strong></label>
<select name="ctr_id" >
<?php
//echo var_dump($contracts);
foreach ($contracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>

<br/><br/>
<input type="submit" value="Submit" id="ama_submit_btn" name="ama_submit_btn" />
<input type="button" value="Cancel" id="ama_cancel_btn" />
</form>
</div>
<!-- amacheck panel //-->


<!-- locums pass panel //-->
<div id="loc_pass_panel" class="p0pup">
<form name="loc_pass_form" method="post" action="" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="plac_status" value="3">
<input type="hidden" name="an_name" value="<?php echo $ar["ctct_name"]; ?>">
<input type="hidden" name="re" value="0">
<input type="hidden" name="n" value="<?php echo $_GET["n"]; ?>">
<input type="hidden" name="srs" value="<?php echo $_GET["srs"]; ?>">
<input type="hidden" name="act_ret" value="15">

<input type="hidden" name="empemail" value="">
<input type="hidden" name="phid" value="">
<input type="hidden" name="empuser" value="">

<strong>Midlevel Pass to Locums</strong><br/><br/>

<label>Pass to:</label>
<select name="emp_id" size="1" >
<?php
			foreach ($rec as $key=>$val)
			{
				echo "<option value='".$key."'>";				
				echo $val;
				echo "</option>";
			}
		?>
</select>
<br/>
<div class="row">
<div class="span3">
<label>Pinnacle contact name:</label> <input type="text" size="40" name="empname" value="<?php echo $_COOKIE["realname"]; ?>">
</div>
<div class="span3">
<label>Best time to call to discuss:</label> <input type="text" size="30" name="emptime" value="">
</div>
</div>

<div class="row">
<div class="span3">
<label>Provider Name:</label><input type="text" size="40" name="phname" value='<?php echo $ar["ctct_name"]; ?>'>
</div>
<div class="span3">
<label>Title:</label><input type="text" size="6" name="title" value='<?php echo $ar["ctct_title"]; ?>'>
</div>
</div>

<div class="row">
<div class="span3">
<label>Address 1:</label><input type="text" size="60" name="addr1" value='<?php echo $ar["ctct_addr_1"]; ?>' />
</div>
<div class="span3">
<label>Address 2:</label><input type="text" size="60" name="addr2" value='<?php echo $ar["ctct_addr_2"]; ?>'>
</div>
</div>

<div class="row">
<div class="span3">
<label>City, State, Zip:</label><input type="text" size="60" name="addr3"  value='<?php echo $ar["ctct_addr_c"].", ".$ar["ctct_st_code"]." ".$ar["ctct_addr_z"]; ?>'>
</div>
<div class="span3">
<label>Phone Number:</label><input type="text" size="40" name="phone" value='<?php echo $ar["ctct_phone"]; ?>'>
</div>
</div>

<div class="row">
<div class="span3">
<label>Email Address:</label><input type="text" size="60" name="email" value="<?php echo $ar["ctct_email"]; ?>">
</div>
<div class="span3">
<label>Category:</label><input type="text" size="60" name="spec" value="<?php echo $ar["an_type"]; ?>">
</div>
</div>

<div class="row">
<div class="span3">
<label>Board Certified:</label><input type="text" size="6" name="bcbe" value="<?php echo $ar["an_bc"]; ?>">
</div>
<div class="span3">
<label>Licenses:</label><input type="text" name="licenses" size="30" value="<?php echo $ar["an_licenses"]; ?>">
</div>
</div>

<div class="row">
<div class="span3">
<label>Actually talked to Dr. about locums?</label>
	<input type="radio" name="talked" value="Yes">&nbsp;Yes&nbsp;
	<input type="radio" name="talked" value="No">&nbsp;No <br/><br/>
</div>
<div class="span3">
<label>Currently working with PHG?</label>
	<input type="radio" name="current" value="Yes">&nbsp;Yes&nbsp;
	<input type="radio" name="current" value="No">&nbsp;No<br/><br/>
</div>
</div>

<div class="row">
<div class="span3">
<label>If yes, go through PHG contact first?</label>
	<input type="radio" name="through" value="Yes">&nbsp;Yes&nbsp;
	<input type="radio" name="through" value="No">&nbsp;No
</div>
<div class="span3">
<label>Best time to call:</label>
	<input type="text" name="besttime" size="40" value="">
</div>
</div>

<div class="row">
<div class="span3">
<label>Current situation/type of position desired:</label>
	<textarea name="situation" cols="60" rows="4"></textarea>	
</div>
<div class="span3">

<br/><br/><br/>	
<input type="submit" value="Submit" id="loc_pass_submit_btn" name="loc_pass_submit_btn" class="btn-large btn" />
<input type="button" value="Cancel" id="loc_pass_cancel_btn" class="btn-large btn" />

</div>
</div>

</form>
</div>
<!-- locums pass panel //-->



<div id="sched_activity_div" class="p0pup" style="">
<strong>Midlevel Schedule Activity</strong><br/><br/>
<form  method="post">
	 <input type="hidden" name="act_t_x" id="act_tx" value="">
	 <input type="hidden" name="act_ref" value="<?php echo $id; ?>">
	 <input type="hidden" name="act_ret" value="15"><!-- midlevel -->
	 <input type="hidden" name="act_ct" value="<?php echo $ar["an_ctct_id"]; ?>">
	<strong><?php echo $ar["an_id"]; ?></strong> - <?php echo $ar["ctct_name"]; ?><br/><br/>
	<strong>Activity:</strong>
	<select size="1" name="activ_type" id="act_t">
	<?php
	
			foreach ($act as $key=>$val)
			{
				echo "<option value='".($val['act_code']+$val['act_need_note']*1000)."'>";				
				echo $val['act_name'];
				echo "</option>";
				
			}
		?>
	</select><br/>
	
	<label><strong>Date:</strong></label> <input type="text" name="schedact_date" id="schedact_datetxt" value="" class="date"/>
	<input type="hidden" name="schedact_date" id="schedact_date" value=""/>
	
	<label><strong>Time:</strong></label>
	<select  name="schedact_hrtxt" id="schedact_hrtxt" class="time" >
		<option value="00">0</option>		
		<option value="01">1</option>
		<option value="02">2</option>
		<option value="03">3</option>
		<option value="04">4</option>
		<option value="05">5</option>
		<option value="06">6</option>
		<option value="07">7</option>
		<option value="08">8</option>
		<option value="09">9</option>
		<option value="10">10</option>
		<option value="11">11</option>
		<option value="12">12</option>
		<option value="13">13</option>
		<option value="14">14</option>
		<option value="15">15</option>
		<option value="16">16</option>
		<option value="17">17</option>
		<option value="18">18</option>
		<option value="19">19</option>
		<option value="20">20</option>
		<option value="21">21</option>
		<option value="22">22</option>
		<option value="23">23</option>
		<option value="24">24</option>
		
		<!--<option value="13:00">1:00 PM</option>
		<option value="14:00">2:00 PM</option>
		<option value="15:00">3:00 PM</option>
		<option value="16:00">4:00 PM</option>
		<option value="17:00">5:00 PM</option>
		<option value="18:00">6:00 PM</option>
		<option value="19:00">7:00 PM</option>
		<option value="08:00">8:00 PM</option>
		<option value="09:00">9:00 PM</option>
		<option value="10:00">10:00 PM</option>
		<option value="11:00">11:00 PM</option>-->
		
	</select>
	:
	<select  name="schedact_mintxt" id="schedact_mintxt"  class="time">
		<option value="00">00</option>
		<option value="05">05</option>
		<option value="10">10</option>
		<option value="15">15</option>
		<option value="20">20</option>
		<option value="25">25</option>
		<option value="30">30</option>
		<option value="35">35</option>
		<option value="40">40</option>
		<option value="45">45</option>
		<option value="50">50</option>
		<option value="55">55</option>		
		
	</select> <br/>
	
	<label><strong>User:</strong></label>
	<select size="1" name="act_user" id="act_t">
	<?php
	
			foreach ($users as $key=>$val)
			{
				echo "<option value='".$key."'>";				
				echo $val;
				echo "</option>";
			}
		?>
	</select>
	
	
	<label><strong>Notes:</strong></label>
	<textarea name="sched_act_notes" id="sched_act_notes"></textarea>
	<br/>
	
	<input type="submit" value="Submit" id="sched_submit_btn" name="sched_submit_btn" />
<input type="button" value="Cancel" id="sched_cancel_btn" />
</form>	
	 
</div>


<!-- add source panel //-->
<div id="addsource_panel" class="p0pup">
<form name="addsource_form" method="post" action="" >
<input type="hidden" name="an_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="an_name" value="<?php echo $ar["ctct_name"]; ?>">
<input type="hidden" name="sp" value="<?php echo $ar["ph_spec_main"]; ?>">
<strong>Add Source</strong><br/><br/>

<label><strong>Contract:</strong></label>
<select name="addsource_ctr_id" id="addsource_ctr_id" >
<?php
//echo var_dump($contracts);
foreach ($contracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>

<br/><br/>

<label><input type="radio" name="is_dm" id="isdm1" checked value="1"> Direct Mail</label>
	     <input type="text" name="dm_code" value="" maxlength="2" size="4" title="Campaign Code (2 symbols)"> code<br>
	   <label><input type="radio" name="is_dm" id="isdm3" value="3"> www.PHG.com</label><br>
	   <label><input type="radio" name="is_dm" id="isdm2" value="4"> PhysicianCareer</label><br>
	   <label><input type="radio" name="is_dm" id="isdm4" value="5"> Physician Work</label><br>
	   <label><input type="radio" name="is_dm" id="isdm5" value="6"> Email Campaigns</label><br>
	   <input type="radio" name="is_dm" id="isdm0" value="0">
<select name="source" id="srctx">
<option value="Unspecified">&nbsp;</option>
<?php
//echo var_dump($contracts);
foreach ($sources as $key=>$val)
{
	//echo "<option value='".$val['src_id']."'>";		
	echo "<option value='".$val['src_name']."'>";				
	echo $val['src_sp_code']." - ".$val['src_name']." - ".$val['src_price'];
	echo "</option>";
	/*echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";*/
				
}
?>
</select>

<label><strong>Date:</strong></label> <input type="text" name="addsource_date" id="addsource_datetxt" value="" class="date"/>
	<input type="hidden" name="addsource_date" id="addsource_date" value=""/>
<br/><br/>

<input type="submit" value="Submit" id="addsource_submit_btn" name="addsource_submit_btn" />
<input type="button" value="Cancel" id="addsource_cancel_btn" />
</form>
</div>
<!-- add source panel //-->

<!-- assessment panel //-->
<div id="candass_panel" class="p0pup">
<form name="candass_form" method="post" action="" target="_blank" >
<input type="hidden" name="ph_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="as_nurse" value="1" />
<br/><br/>

<label><strong>Contract:</strong></label>
<select name="candass_ctr_id" id="candass_ctr_id">
<?php
//echo var_dump($contracts);
foreach ($asscontracts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>

<br/><br/>
<input type="submit" value="Submit" id="candass_submit_btn" name="candass_submit_btn" />
<input type="button" value="Cancel" id="candass_cancel_btn" />
</form>
</div>
<!-- assessment panel //-->

<!-- pending panel //-->
<div id="pending_panel" class="p0pup">
<form name="pending_form" method="post" >
<input type="hidden" name="ph_id" value="<?php echo $ar["an_id"]; ?>">
<input type="hidden" name="pend_status" value="10">
<input type="hidden" name="ph_name" value="<?php echo $ar["ctct_name"]; ?>">
<input type="hidden" name="pipl_emp_id" value="">
<!--<input type="hidden" name="act_ret" value="15">-->
<!--<input type="hidden" name="addon" value="see below">-->
<strong>Pending</strong><br/><br/>

<label><strong>Contract:</strong></label>
<select name="ctr_id" >
<?php
//echo var_dump($contracts);
if($_COOKIE["dept"]=='A' || count($mycontracts)<=0)
	$conts = $contracts;
else
	$conts = $mycontracts;
foreach ($conts as $key=>$val)
{
	echo "<option value='".$val['ctr_id']."'>";				
	echo $val['ctr_no']." ".$val['ctr_spec']." ".$val['ctr_location_c']." ".$val['ctr_location_s'];
	echo "</option>";
				
}
?>
</select>
<label><strong>Pending Date:</strong></label>

<input type="text" name="pend_datetxt" id="pend_datetxt" value="" class="date"/>
<input type="hidden" name="pend_date" id="pend_date" value=""/>


<br/><br/>
<input type="submit" value="Submit" id="pend_submit_btn" name="pend_submit_btn" />
<input type="button" value="Cancel" id="pend_cancel_btn" />
</form>
</div>
<!-- pending panel //-->

<script>
pageLoad();

</script>
<?php

echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-pro'));
