<?php
// module/Pinnacle/view/pinnacle/report/clientactivity.phtml:
// Summary report

$title = 'System Activity Review Report';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');

//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');
/*
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');*/

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');


//$icnt = 0; $tcnt = 0; $prevcliid = 0; $scls = '';

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<style>
.cour {font-family: courier }
</style>
<script>
function pageLoad() { //need to force calendar load   
//$(document).ready(function() {         
			//alert('test');
			//$( "#calendardiv" ).datepicker({altFormat: "yy-mm-dd",  altField: "#cal_date", onSelect: calendarClick()});
			$( "#start_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#start_date"});
			$( "#end_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#end_date"});
}
</script>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<form action="/public/download_report.php" method="post">
<input type="hidden" name="list" value="<?php echo $ar[1]; ?>" />
<input type="submit" value="Download CSV file" name="csv_submit" />
</form>

<?php
    //$form->setAttribute('action', $this->url('report', array('action' => 'rptdataentry')));
    //$form->get('submit')->setAttribute('class','btn btn-success btn-large');
    //$form->prepare();

   // echo $this->form()->openTag($form);
	
	
	
?>
<div class="row"> <div class="span12">&nbsp;</div></div>

<form action="" method="post">
<div class="row">
 <div class="span3">
<label><strong>Start Date:</strong></label> <input type="text" name="start_datetxt" id="start_datetxt" value="" class="date"/>
	<input type="hidden" name="start_date" id="start_date" value=""/>
</div>
 <div class="span4">
<label><strong>End Date:</strong></label> <input type="text" name="end_datetxt" id="end_datetxt" value="" class="date"/>
	<input type="hidden" name="end_date" id="end_date" value=""/>	
	<input type="submit" value="Submit" name="submitdate" />
</div>
</div>
</form>	
	<br/>



<div class="row">
    <div class="span12">
	<form action="" method="post" name="form1" id="form1" >


<?php
echo $ar[0];
?>
	


<br/><br/>
<input type="submit" value="Submit Comments" name="comments_submit" class="btn btn-large" />
</form>
</div>
</div>
 


<div style="clear:both;">&nbsp;</div>
<script>
pageLoad();
</script>
<?php

    //echo $this->form()->closeTag();
?>

<?php
echo $this->partial('reportfooter.phtml', array('phguser' => $phguser));
echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-rep'));
