<?php
// module/Pinnacle/view/pinnacle/report/rptsyspresents.phtml:
// Summary report
$title='System Activity Report';
   
   
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');

//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');
/*
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');*/

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');




if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script style="text/javascript">
function pageLoad() { //need to force calendar load            
			//alert('test');
			$( "#startdatetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#startdate"});
			$( "#enddatetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#enddate"});
			//$('#schedact_timetxt').timepicker();//{ 'timeFormat': 'H:i' });
}
</script>
<style>
h1 { font-size: 16px; }
.alert_bld { font-weight: bold; color: red; }
.bleu_bld { font-weight: bold; color: navy; }
.bld { font-weight: bold; color: black; }
table td{ padding: 5px;  }
label { display: inline; }
.nobg, .nobg td { border: 1px solid black }
</style>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $form->setAttribute('action', $this->url('report', array('action' => 'rptsyspresents')));
    //$form->get('submit')->setAttribute('class','btn btn-success btn-large');
    $form->prepare();

    echo $this->form()->openTag($form);
	//echo var_dump($arr);
	
	//$start  = mktime(0, 0, 0, date("m")  , date("d")-14, date("Y"));	
	//$end = mktime(0, 0, 0, date("m")  , date("d")+14, date("Y")); //time();
?>





<div class="row">
    <div class="span12">
	<form action="" method="post">
	
<table>
	<tr>
	
	<td>
	<label>From Month:</label>
	</td>
   <td>
   <select size="1" name="mon1" >
   <option  value="01">January</option>
   <option  value="02">February</option>
   <option  value="03">March</option>
   <option  value="04">April</option>
   <option  value="05">May</option>
   <option  value="06">June</option>
   <option  value="07">July</option>
   <option  value="08">August</option>
   <option  value="09">September</option>
   <option  value="10">October</option>
   <option  value="11">November</option>
   <option  value="12">December</option>
   </select> 
   </td>
   <td>
	<label>Year:</label> <input type="text" name="yer1" maxlength="4" value="<?php if($_POST["yer1"]!=''){ echo $_POST["yer1"]; } else { echo "1996"; }?>" style="width: 50px">
   </td>
   <td>	
	
	<label>System:</label>	
	</td>
   <td>
	<input name="sys" type="text" id="sys" value="<?php echo $_POST["sys"]; ?>">
	</td>
	<td><input name="nosys" type="checkbox"   value="1"> Reverse Search</td>
	</tr>
	
	<tr>
	<td>
	<label>To Month:</label>
	</td>
   <td>
   <select size="1" name="mon2">
   <option <?php if(date('m')=="01"){ echo "selected"; } ?> value="01">January</option>
   <option <?php if(date('m')=="02"){ echo "selected"; } ?> value="02">February</option>
   <option <?php if(date('m')=="03"){ echo "selected"; } ?> value="03">March</option>
   <option <?php if(date('m')=="04"){ echo "selected"; } ?> value="04">April</option>
   <option <?php if(date('m')=="05"){ echo "selected"; } ?> value="05">May</option>
   <option <?php if(date('m')=="06"){ echo "selected"; } ?> value="06">June</option>
   <option <?php if(date('m')=="07"){ echo "selected"; } ?> value="07">July</option>
   <option <?php if(date('m')=="08"){ echo "selected"; } ?> value="08">August</option>
   <option <?php if(date('m')=="09"){ echo "selected"; } ?> value="09">September</option>
   <option <?php if(date('m')=="10"){ echo "selected"; } ?> value="10">October</option>
   <option <?php if(date('m')=="11"){ echo "selected"; } ?> value="11">November</option>
   <option <?php if(date('m')==12){ echo "selected"; } ?> value="12">December</option>
   </select>
   </td>
   <td>
	<label>Year:</label> <input type="text" name="yer2"  maxlength="4" value="<?php if($_POST["yer2"]!=''){ echo $_POST["yer2"]; } else { echo  date('Y'); }?>" style="width: 50px">
   </td>
   <td>	
	
<label for="demo-select">Specialty:</label>
</td>
   <td>
   <?php //echo var_dump($specs); ?>
    <select name="spec" class="cour">
        <?php
	//echo var_dump($specs);
	$nbsp = array();
	$nbsp[0] = "&nbsp;&nbsp;&nbsp;";
	$nbsp[1] = "&nbsp;&nbsp;";
	$nbsp[2] = "&nbsp;";
	$nbsp[3] = "";
	
			foreach ($specs as $key=>$val)
			{		//(RS("skill") = "--" and IsNull(RS0("ph_skill")) OR RS0("ph_skill")=RS("skill") OR RS("skill") = "  " and IsNull(RS0("ph_skill"))
				$code = $val["sp_code"].$nbsp[strlen($val["sp_code"])];
				echo "<option value='".$val["sp_code"]."|".$val["skill"]."'";
				//if(strtoupper($val["sp_code"])==strtoupper($_POST["ph_spec_main"]) && ($val["skill"]=="--" && ($ar["ph_skill"]==""||$ar["ph_skill"]==null) || $ar["ph_skill"]==$val["skill"] || $ar["ph_skill"] == "  " && ($ar["ph_skill"]==""||$ar["ph_skill"]==null) ))				
					//echo "selected";
				echo ">";				
				echo $code."&nbsp;".$val['spec'];
				echo "</option>";
			}
?>
    </select> 
<input type="submit" value="Submit" name="submitbtn" class="btn" />	
	</td>
	</tr>
	


</table>
	</form>

<br/><br/>
<?php //echo "HERE"; ?>	

 <?php echo $table; ?>
 

</div>
</div>
 


<div style="clear:both;">&nbsp;</div>
<script>
pageLoad();
</script>
<?php

    echo $this->form()->closeTag();
?>

<?php
echo $this->partial('reportfooter.phtml', array('phguser' => $phguser));
echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-rep'));
