<?php
// module/Pinnacle/view/pinnacle/report/rptsrcisc.phtml:
// Summary report

$months = array(1 => 'Jan.', 2 => 'Feb.', 3 => 'Mar.', 4 => 'Apr.', 5 => 'May', 6 => 'Jun.', 7 => 'Jul.', 8 => 'Aug.', 9 => 'Sep.', 10 => 'Oct.', 11 => 'Nov.', 12 => 'Dec.');

if(!isset($_GET))
	$_GET=$_POST;

$title = 'ISC Report - '.date('Y-m-d');

  
   
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');

//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');
/*
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');*/

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');




if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script style="text/javascript">
function pageLoad() { //need to force calendar load            
			//alert('test');
			//$( "#startdatetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#startdate"});
			//$( "#enddatetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#enddate"});
			//$('#schedact_timetxt').timepicker();//{ 'timeFormat': 'H:i' });
}
</script>
<style>
h1 { font-size: 16px; }
.alert_bld { font-weight: bold; color: red; }
.bleu_bld { font-weight: bold; color: navy; }
.bld { font-weight: bold; color: black; }
table { background-color: #ffffff; }
label { display: inline; }
</style>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $form->setAttribute('action', $this->url('report', array('action' => 'rpthotlists')));
    //$form->get('submit')->setAttribute('class','btn btn-success btn-large');
    $form->prepare();

    echo $this->form()->openTag($form);
	//echo var_dump($arr);
	
	
?>





<div class="row">
    <div class="span12">


<br/><br/>
	
<table class="nobg" width="100%" border=1 cellspacing=0 cellpadding=1><thead><tr><td>&nbsp;</td>
<td class="bld ctr Large"><a class="ndec" href="?ordr=0">Contract</a></td>
<td class="bld ctr Large"><a class="ndec" href="?ordr=1">Date</a></td>
<td class="bld ctr Large"><a class="ndec" href="?ordr=2">Recruiter</a></td>
<td class="bld ctr Large"><a class="ndec" href="?ordr=3">Spec</a></td>
<td class="bld ctr Large"><a class="ndec" href="?ordr=4">City</a></td>
<td class="bld ctr Large"><a class="ndec" href="?ordr=5">State</a></td>
<td class="bld ctr Large"><a class="ndec" href="?ordr=6">Facility</a></td>
<td class="bld ctr Large">Price</td>
</tr></thead><tbody>
 
<?php
$icnt=0;
//setlocale(LC_MONETARY, 'en_US');
foreach($arr as $key=>$val)
{
$icnt+=1;
?>

<tr>
 <td><?php echo $icnt; ?></td>
 <td><a class="ndec" href="<?php echo $this->basePath(); ?>/contract/view/<?php echo $val["ctr_id"]; ?>"><?php echo $val["ctr_no"]; ?></a></td>
 <td><?php echo $val["ctr_date"]; ?></td>
 <td><?php echo $val["emp_uname"]; ?></td>
 <td><?php if($val["ctr_nurse"]==1){echo "midl."; }?><?php echo $val["ctr_spec"]; ?></td>
 <td><?php echo $val["ctr_location_c"]; ?></td>
 <td><?php echo $val["ctr_location_s"]; ?></td>
 <td><a class="ndec" href="<?php echo $this->basePath(); ?>/client/view/<?php echo $val["cli_id"]; ?>"><?php echo $val["ctct_name"]; ?></a></td>
 <td align="right">$<?php echo number_format( $val["csr_price"], 2); ?></td>
</tr>

<?php	
	
}
//$scnt = $scnt + $icnt;
?>

</tbody></table>


</div>
</div>
 


<div style="clear:both;">&nbsp;</div>
<script>
pageLoad();
</script>
<?php

    echo $this->form()->closeTag();
?>

<?php
echo $this->partial('reportfooter.phtml', array('phguser' => $phguser));
echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-rep'));
