<?php
// module/Pinnacle/view/pinnacle/report/usersumst.phtml:
// Summary report

$title = 'Recruiting Performance Summary - '.$ldate;
$this->headTitle($title);

$icnt = 0; $tcnt = 0; $prevcliid = 0; $scls = '';

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script language="JavaScript"><!--
	function loaded() {
	   try { parent.frames.phgtop.sim_click("rep_a"); } catch (e) { } finally {} //debug
	}

      // Load the Google Visualization API and the barchart package.
	  // see http://code.google.com/apis/chart/interactive/docs/gallery.html
      google.load('visualization', '1.0', {packages:['corechart','imagebarchart']});

// -->
</script>
<style>
h1 { font-size: 16px; }
.alert_bld { font-weight: bold; color: red; }
.bleu_bld { font-weight: bold; color: navy; }
.bld { font-weight: bold; color: black; }
table { background-color: #ffffff; }
</style>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $form->setAttribute('action', $this->url('report', array('action' => 'placement')));
    //$form->get('submit')->setAttribute('class','btn btn-success btn-large');
    $form->prepare();

    echo $this->form()->openTag($form);
	//echo var_dump($arr);
?>
<?php

function GetRatio($r1, $r2){
	if($r1==0)
		echo "0:".$r2;
	elseif($r2==0)
		echo $r1.":0";
	elseif($r1==$r2)
		echo "1:1";
	elseif($r1>$r2){
		$r = $r1/$r2;
		echo round($r,1)."&nbsp;<b>:</b>&nbsp;1";
	}
	else{
		$r = $r2/$r1;
		echo "1&nbsp;<b>:</b>&nbsp;".round($r,1);
	}
}

function Lookup($ar, $n, $x){
	if($n>0)
	{	
		for ($i=0; $i<$n; $i++){
			if($ar[$i]==$x){
				return $i;
			}
			//echo $ar[$i]."<br/>";
				//return $i;
		}
	}
	return -1;
}

$empid = $_COOKIE["phguid"];		
?>


<?php
//get current month for example
$beginday=date("Y-m-01");
$lastday=date("Y-m-d");

$nr_work_days = getWorkingDays($beginday,$lastday);
//echo $nr_work_days;

function getWorkingDays($startDate, $endDate){
 $begin=strtotime($startDate);
 $end=strtotime($endDate);
 if($begin>$end){
  //echo “startdate is in the future! <br />”;
  return 0;
 }else{
   $no_days=0;
   $weekends=0;
  while($begin<=$end){
    $no_days++; // no of days in the given interval
    $what_day=date("N",$begin);
     if($what_day>5) { // 6 and 7 are weekend days
          $weekends++;
     };
    $begin+=86400; // +1 day
  };
  $working_days=$no_days-$weekends;
  return $working_days;
 }
}

//start function
$DT0=mktime(0, 0, 0, date("m")  , date("d"), date("Y"));
$calldata2 = false;
$Dt1 = mktime(0, 0, 0, date("m")  , date("d")-1, date("Y")); //' yesterday
$numc = 0;
$calltimes=array();
//echo var_dump($rs);
foreach ($rs as $key=>$val)
{
	//echo $val["call_emp_id"]."<br/>";
	$emps[$numc]=$val["call_emp_id"];
	$sumc[$numc]=$val["sumout"];
	$times[$numc]=$val["timout"];
	$avgt = $val["timout"];

$hours = floor($avgt / 3600);
$mins = floor(($avgt - ($hours*3600)) / 60);
$seconds = floor($avgt % 60);

/*$seconds = $avgt % 60;
$time = ($avgt - $seconds) / 60;
$minutes = $avgt % 60;
$hours = round((($avgt - $minutes) / 60),2);*/
$time = ($avgt - $seconds) / 60;
	
	$atimes[$numc]= gmdate("H:i:s",$avgt);//date('h:i:s',mktime($hours,$minutes,$seconds)); //date('h:i:s',mktime(0,0,$avgt)); //$hours.":".$minutes.":".$seconds; //($avgt/60) $avgt%60;
	$numc = $numc + 1;
	$calldata2 = true;
	$calltimes[$val["call_emp_id"]] = gmdate("H:i:s",$avgt);
	$callnum[$val["call_emp_id"]] = $val["sumout"]/$nr_work_days;
}

//echo date('Y-m-d',$Dt1);
//echo $DT0;

//echo var_dump($emps);
$errth = 0;

$mycat = 0;
        
for ($i = 0; $i<=4; $i++)
{
    $ns[$i]=0;   
	for ($k = 0; $k<=4; $k++)
	{
		$ysum[0][$i][$k] = "0.0"; 
		$ysum[1][$i][$k] = "0.0";
		$ysum[2][$i][$k] = "0.0";
        $msum[0][$i][$k] = "0.0"; 
		$msum[1][$i][$k] = "0.0";
		$msum[2][$i][$k] = "0.0";
		   
	}           
}

foreach ($gl as $key=>$val)
{
	$cat = $val["category"];
	
	$uname[$cat][$ns[$cat]] = $val["uname"];
		$eid[$cat][$ns[$cat]] = $val["emp_id"];
		$est[$cat][$ns[$cat]] = $val["emp_status"];
		
		if ($empid == $eid[$cat][$ns[$cat]] ){
            $mycat = $cat;
            $myns = $ns[$cat];
        }
		//echo $eid[$cat][$ns[$cat]]."<br/>";
		$eind[$cat][$ns[$cat]] = Lookup($emps,$numc,$eid[$cat][$ns[$cat]]);
	   $catg[1][$cat][$ns[$cat]] = $val["goal1"];
	   $catg[2][$cat][$ns[$cat]] = $val["goal2"];
	   $catg[3][$cat][$ns[$cat]] = $val["goal3"];
	   $catg[4][$cat][$ns[$cat]] = $val["goal4"];
	   $cata[1][$cat][$ns[$cat]] = $val["act1"];
	   $cata[2][$cat][$ns[$cat]] = $val["act2"];
	   $cata[3][$cat][$ns[$cat]] = $val["act3"];
	   $cata[4][$cat][$ns[$cat]] = $val["act4"];
	   $matg[1][$cat][$ns[$cat]] = $val["moal1"];
	   $matg[2][$cat][$ns[$cat]] = $val["moal2"];
	   $matg[3][$cat][$ns[$cat]] = $val["moal3"];
	   $matg[4][$cat][$ns[$cat]] = $val["moal4"];
	   $mata[1][$cat][$ns[$cat]] = $val["mact1"];
	   $mata[2][$cat][$ns[$cat]] = $val["mact2"];
	   $mata[3][$cat][$ns[$cat]] = $val["mact3"];
	   $mata[4][$cat][$ns[$cat]] = $val["mact4"];
	   $yatg[1][$cat][$ns[$cat]] = $val["yoal1"];
	   $yatg[2][$cat][$ns[$cat]] = $val["yoal2"];
	   $yatg[3][$cat][$ns[$cat]] = $val["yoal3"];
	   $yatg[4][$cat][$ns[$cat]] = $val["yoal4"];
	   $ns[$cat] = $ns[$cat] + 1;
}

for ($i = 1; $i<=4; $i++) //...should these been <=?
{    
	for ($k = 1; $k<=4; $k++)
	{
		for ($j = 0; $j<=$ns[$k]-1; $j++) //adjusted this
		{
			$ysum[0][$i][$k] = $ysum[0][$i][$k] + $yatg[$i][$k][$j]; // goal year end totals
			$ysum[1][$i][$k] = $ysum[1][$i][$k] + $cata[$i][$k][$j]; //' act YTD totals
			$ysum[2][$i][$k] = $ysum[2][$i][$k] + $catg[$i][$k][$j]; //' goal YTD totals			
			$msum[1][$i][$k] = $msum[1][$i][$k] + $mata[$i][$k][$j]; //' act month totals
			$msum[2][$i][$k] = $msum[2][$i][$k] + $matg[$i][$k][$j]; //' goal month totals
		}   
	}           
}
//echo var_dump($uname);
?>

<div class="row">
    <div class="span12">
	
<table width="100%" class="nobg ctr" border="1" cellspacing="0" cellpadding="2"><tr>
<td>&nbsp;</td>
<td>AVG Phone time per Day</td>
<td><?php echo$coldate; ?> Placements &amp; &plusmn;to Goal</td>
<td><?php echo$coldate; ?> Interviews &amp; &plusmn;to Goal</td>
<td>Prsnts this month</td>
<td>Placements YTD &amp; &plusmn;to Goal</td>
<td>Interviews YTD &amp; &plusmn;to Goal</td>
<td>IV/Pl Ratio YTD</td>
<td>Present/IV Ratio YTD</td>
</tr>
<?php
  $sumtimes = 0;
  for ($i=0; $i<=$ns[1]-1; $i++)	//not sure of the indexing on this
  {
	if($est[1][$i]>0)
	{
		if($eind[1][$i]<0)
		{
			$atmes = "N/A";
		}
		else{
			$atmes = $atimes[$eind[1][$i]];
			$sumtimes = $sumtimes + $times[$eind[1][$i]];
		}
		//echo var_dump($atimes);
		//other stuff here
		?>
		
<tr>
<td><a class="ndec" href="#userstats.asp?emp_id=<?php echo $eid[1][$i]; ?>"><?php echo $uname[1][$i]; ?></a></td><td><?php echo $atmes; ?></td>
<td><?php echo $mata[1][1][$i]; ?>
<?php if($matg[1][1][$i] > 0){ ?>
(<span class='
	<?php 
	if($mata[1][1][$i] >= $matg[1][1][$i]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Goal: <?php echo $matg[1][1][$i]; ?>"><?php echo ($mata[1][1][$i]-$matg[1][1][$i]); ?>
</span>)
<?php } ?>

</td>
<td>
<?php echo $mata[2][1][$i]; ?>
<?php if($matg[2][1][$i] > 0){ ?>
(<span class='
	<?php 
	if($mata[2][1][$i] >= $matg[2][1][$i]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Goal: <?php echo $matg[2][1][$i]; ?>"><?php echo ($mata[2][1][$i]-$matg[2][1][$i]); ?>
</span>)
<?php } ?>

</td>
<td><?php echo $mata[3][1][$i]; ?></td>

<td>
<?php echo $cata[1][1][$i]; ?>
<?php if($catg[1][1][$i] > 0){ ?>
(<span class='
	<?php 
	if($cata[1][1][$i] >= $catg[1][1][$i]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Annual Goal: <?php echo $yatg[1][1][$i]; ?>"><?php echo ($cata[1][1][$i]-$catg[1][1][$i]); ?>
</span>)
<?php } ?>

</td>
<td>
<?php echo $cata[2][1][$i]; ?>
<?php if($catg[2][1][$i] > 0){ ?>
(<span class='
	<?php 
	if($cata[2][1][$i] >= $catg[2][1][$i]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Annual Goal: <?php echo $yatg[2][1][$i]; ?>"><?php echo ($cata[2][1][$i]-$catg[2][1][$i]); ?>
</span>)
<?php } ?>

</td>
<td class="rite"><?php GetRatio ($cata[2][1][$i], $cata[1][1][$i]);  ?></td>
<td class="rite"><?php GetRatio ($cata[3][1][$i], $cata[2][1][$i]);  ?></td>
</tr>
<?php
if($eid[1][$i]==105 || $eid[1][$i]==24){

$placements = $placements+$mata[1][1][$i];
$placements_goal = $placements_goal+$matg[1][1][$i];
$interviews = $interviews+$mata[2][1][$i];
$interviews_goal = $interviews_goal+$matg[2][1][$i];
$presents = $presents+ $mata[3][1][$i];
$placements_ytd = $placements_ytd+$cata[1][1][$i];
$placements_ytd_goal = $placements_ytd_goal+$catg[1][1][$i];
$interviews_ytd = $interviews_ytd+$cata[2][1][$i];
$interviews_ytd_goal = $interviews_ytd_goal+$catg[2][1][$i];
$act3 = $act3+$cata[3][1][$i];
}

if($eid[1][$i]==2 || $eid[1][$i]==239){

$placements2 = $placements2+$mata[1][1][$i];
$placements_goal2 = $placements_goal2+$matg[1][1][$i];
$interviews2 = $interviews2+$mata[2][1][$i];
$interviews_goal2 = $interviews_goal2+$matg[2][1][$i];
$presents2 = $presents2+ $mata[3][1][$i];
$placements_ytd2 = $placements_ytd2+$cata[1][1][$i];
$placements_ytd_goal2 = $placements_ytd_goal2+$catg[1][1][$i];
$interviews_ytd2 = $interviews_ytd2+$cata[2][1][$i];
$interviews_ytd_goal2 = $interviews_ytd_goal2+$catg[2][1][$i];
$act32 = $act32+$cata[3][1][$i];
}
?>


<?php		
		
	}// end est
  }// end for
  
  $avgt = $sumtimes;
  $days = round($avgt/86400);
  //$avgt = avgt%86400;
  //echo $avgt;
  //echo $days;
?>






<tr>
<td class="bld">Recruiting</td><td><?php echo $days; ?>:<?php echo gmdate('H:i:s', $avgt); //date('h:i:s',mktime(0, ($avgt/60), ($avgt%60))); ?></td>
<td>
<?php echo $msum[1][1][1]; ?> 

(<span class='
	<?php 
	if($msum[1][1][1] >= $msum[2][1][1]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Goal: <?php echo $msum[2][1][1]; ?>"><?php echo ($msum[1][1][1]-$msum[2][1][1]); ?>
</span>)

</td>
<td>
<?php echo $msum[1][2][1]; ?> 

(<span class='
	<?php 
	if($msum[1][2][1] >= $msum[2][2][1]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Goal: <?php echo $msum[2][2][1]; ?>"><?php echo ($msum[1][2][1]-$msum[2][2][1]); ?>
</span>)

</td>
<td><?php echo $msum[1][3][1]; ?></td>
<td>
<?php echo $ysum[1][1][1]; ?> 
(<span class='
	<?php 
	if($ysum[1][1][1] >= $ysum[2][1][1]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Annual Goal: <?php echo $ysum[0][1][1]; ?>"><?php echo ($ysum[1][1][1]-$ysum[2][1][1]); ?>
</span>)

</td>

<td>
<?php echo $ysum[1][2][1]; ?> 
(<span class='
	<?php 
	if($ysum[1][2][1] >= $ysum[2][2][1]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Annual Goal: <?php echo $ysum[0][2][1]; ?>"><?php echo ($ysum[1][2][1]-$ysum[2][2][1]); ?>
</span>)
</td>
<td class="rite"><?php GetRatio ($ysum[1][2][1], $ysum[1][1][1]);  ?></td>
<td class="rite"><?php GetRatio ($ysum[1][3][1], $ysum[1][2][1]);  ?></td>
</tr>

 </table> 

 
 <h1>Marketing Performance Summary - <?php echo $ldate; ?></h1>
<table width="100%" class="nobg ctr" border="1" cellspacing="0" cellpadding="2"><tr>
<td>&nbsp;</td><td><?php echo$coldate; ?> Calls</td>
<td><?php echo$coldate; ?> Retainers &amp; &plusmn;to Goal</td>
<td>New Retainers %MTD &amp; &plusmn;to Goal</td>
<td><?php echo$coldate; ?> Meetings &amp; &plusmn;to Goal</td>
<td>Retainers YTD &amp; &plusmn;to Goal</td>
<td>Meetings YTD &amp; &plusmn;to Goal</td>
<td>Meeting / Retainer Ratio YTD</td>
<td>Call / Meeting Ratio Monthly</td>
</tr>
<?php

$sumca = 0;
  for ($i=0; $i<=$ns[3]-1; $i++)	//not sure of the indexing on this
  {
	if($est[3][$i]>0)
	{
		if($eind[3][$i]<0)
		{
			$smca = "N/A";
		}
		else{
			$smca = $sumc[$eind[3][$i]];
			$sumca = $sumca + $sumc[$eind[3][$i]];
		}
?>

<tr>
<td><a class="ndec" href="userstats.asp?emp_id=<?php echo $eid[3][$i]; ?>"><?php echo $uname[3][$i]; ?></a></td><td><?php echo $smca; ?></td>
<td>
<?php echo $mata[1][3][$i]; ?>
<?php if($matg[1][3][$i] > 0){ ?>
(<span class='
	<?php 
	if($mata[1][3][$i] >= $matg[1][3][$i]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Goal: <?php echo $matg[1][3][$i]; ?>"><?php echo ($mata[1][3][$i]-$matg[1][3][$i]); ?>
</span>)
<?php } ?>

</td>
<td>

	<?php 
	if($mata[1][3][$i] ==0) 
		echo "N/A";
	else
		echo round((($mata[3][3][$i]/$mata[1][3][$i])*100),1)."%";
	if($mata[3][3][$i]>0)
	{
	?>
	(<span class='
	<?php 
	if($mata[3][3][$i] >= $matg[3][3][$i]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
	title="Goal: <?php echo $matg[3][3][$i]; ?>"><?php echo ($mata[3][3][$i]-$matg[3][3][$i]); ?>
	</span>)
	<?php
	}
	?>

</td>
<td>
<?php echo $mata[2][3][$i]; ?>
<?php if($matg[2][3][$i] > 0){ ?>
(<span class='
	<?php 
	if($mata[2][3][$i] >= $matg[2][3][$i]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Goal: <?php echo $matg[2][3][$i]; ?>"><?php echo ($mata[2][3][$i]-$matg[2][3][$i]); ?>
</span>)
<?php } ?>

</td>
<td>
<?php echo $cata[1][3][$i]; ?>
<?php if($catg[1][3][$i] > 0){ ?>
(<span class='
	<?php 
	if($cata[1][3][$i] >= $catg[1][3][$i]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Annual Goal: <?php echo $yatg[1][3][$i]; ?>"><?php echo ($cata[1][3][$i]-$catg[1][3][$i]); ?>
</span>)
<?php } ?>

</td>
<td>
<?php echo $cata[2][3][$i]; ?>
<?php if($catg[2][3][$i] > 0){ ?>
(<span class='
	<?php 
	if($cata[2][3][$i] >= $catg[2][3][$i]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Annual Goal: <?php echo $yatg[2][3][$i]; ?>"><?php echo ($cata[2][3][$i]-$catg[2][3][$i]); ?>
</span>)
<?php } ?>

</td>
<td class="rite"><?php GetRatio($cata[2][3][$i], $cata[1][3][$i]); ?></td>
<td class="rite"><?php 
if($smca=="N/A")
	$smca=0;
GetRatio($smca, $mata[2][3][$i]); 
?>

</td>
</tr>

	
	
<?php
	}//end est
}//end for
?>	

<tr>
<td class="bld">Marketing</td><td><?php echo $sumca;?></td>
<td>
<?php echo $msum[1][1][3]; ?>

(<span class='
	<?php 
	if($msum[1][1][3] >= $msum[2][1][3]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Goal: <?php echo $msum[2][1][3]; ?>"><?php echo ($msum[1][1][3]-$msum[2][1][3]); ?>
</span>)

</td>
<td>
<?php if($msum[1][1][3]==0)
		echo "N/A";
	else
		echo round((($msum[1][3][3]/$msum[1][1][3])*100),2)."%";
?>

(<span class='
	<?php 
	if($msum[1][3][3] >= $msum[2][3][3]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Goal: <?php echo $msum[2][3][3]; ?>"><?php echo ($msum[1][3][3]-$msum[2][3][3]); ?>
</span>)

</td>

<td>
<?php echo $msum[1][2][3]; ?>

(<span class='
	<?php 
	if($msum[1][2][3] >= $msum[2][2][3]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Goal: <?php echo $msum[2][2][3]; ?>"><?php echo ($msum[1][2][3]-$msum[2][2][3]); ?>
</span>)
</td>

<td>
<?php echo $ysum[1][1][3]; ?>

(<span class='
	<?php 
	if($ysum[1][1][3] >= $ysum[2][1][3]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Annual Goal: <?php echo $ysum[0][1][3]; ?>"><?php echo ($ysum[1][1][3]-$ysum[2][1][3]); ?>
</span>)
</td>
<td>
<?php echo $ysum[1][2][3]; ?>

(<span class='
	<?php 
	if($ysum[1][2][3] >= $ysum[2][2][3]) 
		echo "bleu_bld";
	else
		echo "alert_bld";
	?>'
title="Annual Goal: <?php echo $ysum[0][2][3];?>"><?php echo $ysum[1][2][3]-$ysum[2][2][3];?></span>)</td>
<td class="rite"><?php GetRatio($ysum[1][2][3], $ysum[1][1][3]); ?></td>
<td class="rite"><?php GetRatio($sumca, $msum[1][2][3]); ?></td>
</tr>

</table>

<h1>Recruiting Team - <?php echo $ldate; ?></h1>

<?php //echo var_dump($pl);

//echo var_dump($wpl);

echo '<table width="50%" class="nobg ctr" border="1" cellspacing="0" cellpadding="2">';
echo '<tr><th></th><th>Avg. Phone Time per day</th><th>Avg. Calls per day</th><th>Passes<br/>MTD</th><th>Passes<br/>Last wk</th></tr>';
foreach($pl as $k=>$v)
{
	$i=$v["emp_id"];
	//echo $i."<br/>";
	if($i!=261 && $i!=271 && $i!=268) //temp fix for jan to remove old emps
	echo '<tr><td><a class="ndec" href="#userstats.asp?emp_id='.$i.'">'.$v["rec_from"].'</a></td><td>'.$calltimes[$i].'</td><td>'.round($callnum[$i]).'</td><td>'.$v["cnt"].'</td><td>'.$wpl[$k]["cnt"].'</td></tr>';

}
echo '</table>';
?>

<h1>Locums - <?php echo $ldate; ?></h1>

<table  class="nobg ctr" border="1" cellspacing="0" cellpadding="2" style="float:right; margin-right: 20%">
<tr><th>Outstanding Contracts</th><td ><?php echo $lt[count($lt)-1]["outstanding_contracts"]; ?></td></tr>
<tr><th>Open Positions</th><td ><?php echo $lt[count($lt)-1]["open_positions"]; ?></td></tr>
</table>

<?php //echo var_dump($lt);

//echo var_dump($mata);

echo '<table width="60%" class="nobg ctr" border="1" cellspacing="0" cellpadding="2">';
echo '<tr><th></th><th>Avg. Calls per day</th><th>Presents Last Week</th><th>YTD</th><th>Curr. Month</th><th>Next Month</th></tr>';
foreach($lt as $k=>$v)
{
	$i=$v["emp_id"];
	//echo $i."<br/>";
	echo '<tr><td><a class="ndec" href="#userstats.asp?emp_id='.$i.'">'.$v["user_mod"].'</a></td><td>'.round($callnum[$i]).'</td><td>'.$plt[$i]["cnt"].'</td><td align="right">'.number_format($v["ytd"],2).'</td><td align="right">'.number_format($v["current_mon"],2).'</td><td align="right">'.number_format($v["next_mon"],2).'</td></tr>';

}
echo '</table>';

/*
echo '<table width="50%" class="nobg ctr" border="1" cellspacing="0" cellpadding="2">';
echo '<tr><th></th><th>Avg. Phone Time per day</th><th>Avg. Calls per day</th><th>Presents Last Week</th></tr>';
foreach($plt as $k=>$v)
{
	$i=$v["user_mod_id"];
	//echo $i."<br/>";
	echo '<tr><td><a class="ndec" href="#userstats.asp?emp_id='.$i.'">'.$v["user_mod"].'</a></td><td>'.$calltimes[$i].'</td><td>'.round($callnum[$i]).'</td><td>'.$v["cnt"].'</td></tr>';

}
echo '</table>';*/
?>
<small><em>(Numbers are before expenses)</em></small>
<br/>
<table  class="nobg ctr" border="1" cellspacing="0" cellpadding="2" style="display:none">
<tr><th>YTD</th><th>Current Month</th><th>Next Month</th><th>Net +/-</th><th>%GP MTD</th><th>%GP YTD</th></tr>
<tr><td><?php echo $lt["ytd"]; ?></td><td><?php echo $lt["current_mon"]; ?></td><td><?php echo $lt["next_mon"]; ?></td><td><?php echo $lt["net_add"]; ?></td><td><?php echo $lt["gp_mtd"]; ?></td><td><?php echo $lt["gp_ytd"]; ?></td></tr>
<tr><th>Outstanding Contracts</th><td colspan="5"><?php echo $lt["outstanding_contracts"]; ?></td></tr>
<tr><th>Open Positions</th><td colspan="5"><?php echo $lt["open_positions"]; ?></td></tr>
</table>

<p style="clear:both"></p>
<h1>Physician Career - <?php echo $ldate; ?></h1>

<table  class="nobg ctr" border="1" cellspacing="0" cellpadding="2" style="float: right; margin-right: 20%">
<tr><th>Revenue MTD</th><th>Revenue YTD</th></tr>
<tr><td><?php echo $pc["rev_mtd"]; ?>%</td><td><?php echo $pc["rev_ytd"]; ?>%</td></tr>
</table>

<?php //echo var_dump($pl);
$pcc = array();
$pcc[0]["user_mod_id"]=227;
$pcc[0]["user_mod"]="mberg@phg.com";
$pcc[1]["user_mod_id"]=101;
$pcc[1]["user_mod"]="tbroxterman@phg.com";
//echo var_dump($mata);

echo '<table width="50%" class="nobg ctr" border="1" cellspacing="0" cellpadding="2">';
echo '<tr><th></th><th>Avg. Phone Time per day</th><th>Avg. Calls per day</th></tr>';
foreach($pcc as $k=>$v)
{
	$i=$v["user_mod_id"];
	//echo $i."<br/>";
	echo '<tr><td><a class="ndec" href="#userstats.asp?emp_id='.$i.'">'.$v["user_mod"].'</a></td><td>'.$calltimes[$i].'</td><td>'.round($callnum[$i]).'</td></tr>';

}
echo '</table>';

//echo var_dump($pc);
?>
<br/>
<table  class="nobg ctr" border="1" cellspacing="0" cellpadding="2" style="display:none">
<tr><th>Monthly Goal</th><th>Monthly Total</th><th>%</th></tr>
<tr><td><?php echo $pc["monthly_goal"]; ?></td><td><?php echo $pc["monthly_amt"]; ?></td><td><?php echo round(($pc["monthly_amt"]/$pc["monthly_goal"])*100); ?>%</td></tr>
</table>



</div>
</div>

<div style="clear:both;">&nbsp;</div>
<?php

    echo $this->form()->closeTag();
?>
<?php
echo $this->partial('reportfooter.phtml', array('phguser' => $phguser));
echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-rep'));
