<?php
// module/Pinnacle/view/pinnacle/client/addfuzion.phtml:
// Contract Search

$title = 'Add Fuzion Contract';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/js/vendor/datepicker/css/datepicker.css');

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.10.0.min.js', 'text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js', 'text/javascript');

//$this->headScript()->appendFile('http://code.jquery.com/jquery-migrate-1.2.1.min.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/JSON-js-master/json2.js', 'text/javascript');
/*
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/datepicker.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/eye.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/utils.js', 'text/javascript');
$this->headScript()->appendFile($this->basePath() . '/js/vendor/datepicker/js/booking_layout.js?ver=1.0.2', 'text/javascript');*/

$this->headLink()->prependStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css');
$this->headLink()->prependStylesheet('/resources/demos/style.css');

if( $messages )
    echo $this->partial('flashheader.phtml', array('messages' => $messages));
?>
<style>
h4 { text-align: center; }
.inline { font-weight: bold; /*display: block; float: left; width: 90px;*/ }
</style>
<script style="text/javascript">
function pageLoad() { //need to force calendar load            
			//alert('test');
			
			 $( "#fu_datetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#fu_date"});
			 $( "#fu_renewaltxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#fu_renewal"});
			 $( "#fu_starttxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#fu_start"});
			 $( "#fu_invoicetxt" ).datepicker({altFormat: "yy-mm-dd",  altField: "#fu_invoice"});
			
}




</script>


<?php

?>

<h1 ><?php echo $this->escapeHtml($title); ?></h1>

<?php
    //$form->setAttribute('action', $this->url('resort', array('action'=>'midlevels')));
    //$form->get('submit')->setAttribute('type','button');
  
    $form->prepare();
    //$maillist = $this->formRow($form->get('mail_list'));

    echo $this->form()->openTag($form);
	//echo var_dump($ar);
?>


<p style="text-align:center; color: red"><?php echo $message; ?></p>


<input type="hidden" name="cli_id" value="<?php echo $cli_id; ?>">
<input type="hidden" name="fu_id" value="0">
	
	<input type="hidden" name="fu_master" value=''>
	<input type="hidden" name="srs" value="<?php echo $_GET["srs"]; ?>">
	<input type="hidden" name="n" value="<?php echo $_GET["n"]; ?>" />


<div class="row">
    <div class="span4">
	<label class="inline">ID #: </label>NEW
	
    </div>  
	<div class="span6">
	<label class="inline">Status:</label>
	<select name="fu_status"  size="1">
		<option value="0" >Inactive</option>
		<option value="1" >Active</option>
		<option value="2" >Expired</option>
		<option value="4" >Canceled</option>
	</select> 
	This is a renewal: 
      <input name="fu_nonew" type="checkbox"  id="fu_nonew"  value="1"> Yes
    </div>
</div>


<div class="row">
	<div class="span4">
		<label class="inline">Fuzion Account: </label>
		<input type="text" name="fu_acct"  size="20" maxlength="10" value=""/>
	</div>	
	<div class="span6">
	<label class="inline">Date Signed:</label>
	<input type="text" id="fu_datetxt" name="fu_datetxt" />
	<input type="hidden" name="fu_date" id="fu_date" value="">
	</div>	
</div>


<div class="row">
	<div class="span4">
		<label class="inline">Length in years: </label>
		<input type="text" name="fu_length"  size="20" maxlength="10" value=""/>
	</div>	
	<div class="span6">
		<label class="inline">Renewal Date:</label>
		<input type="text" name="fu_renewaltxt" id="fu_renewaltxt"  size="20" maxlength="10" value=""/>
		<input type="hidden" name="fu_renewal" id="fu_renewal" value="">
	</div>	
</div>

<div class="row">
	<div class="span4">
		<label class="inline">Start Date: </label>
		<input type="text" name="fu_starttxt" id="fu_starttxt"  size="20" maxlength="10" value=""/>
		<input type="hidden" name="fu_start" id="fu_start" value=""/>
	</div>	
	<div class="span6">
		<label class="inline">Invoice Date:</label>
		<input type="text" name="fu_invoicetxt" id="fu_invoicetxt" size="20" maxlength="10" value=""/>
		<input type="hidden" name="fu_invoice" id="fu_invoice" value="">
	</div>	
</div>

<div class="row">
	<div class="span4">
		<label class="inline">Amount, $: </label>
		<input type="text" name="fu_amount"  size="20" maxlength="20" value=""/>
	</div>	
	<div class="span6">
		<label class="inline">Notes:</label>
		<textarea name="fu_notes"  >
		
		</textarea>
	</div>	
</div>





	


<br/><br/>
<p><small>If you need to recalculate the date, delete old value. New value will be recalculated automatically</small></p>
<input type="submit" name="submit" value="Submit" class="btn"/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="<?php echo $this->basePath(); ?>/client/view/<?php echo $cli_id; ?>">Go Back to Client</a>


<div style="clear:both">&nbsp;</div>
<?php
    echo $this->form()->closeTag();
?>






<script>
pageLoad();

</script>
<?php

echo $this->partial('sysfooter.phtml', array('menuid' => 'phg-nav-cli'));
